name: Start containers
description: Start containers

runs:
  using: 'composite'
  steps:
    - name: Start containers
      shell: bash
      run: |
        docker network create dockernet
        GITHUB_ACTION_UUID=1001 docker compose -f docker-compose.yml up -d
