# Admin's routing
sonata_user:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /{_locale}/admin
  requirements:
      _locale: '%app_locales%'
  defaults:
      _locale: '%locale%'

admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /{_locale}/admin
  requirements:
      _locale: '%app_locales%'
  defaults:
      _locale: '%locale%'

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /{_locale}/admin
  requirements:
      _locale: '%app_locales%'
  defaults:
      _locale: '%locale%'

sonata_user_admin_security:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /{_locale}/admin
  requirements:
      _locale: '%app_locales%'
  defaults:
      _locale: '%locale%'

sonata_user_admin_security_logout:
  path:  /{_locale}/logout
  defaults:
      _controller: FOSUserBundle:Security:logout
      _locale: '%locale%'
  requirements:
      _locale: '%app_locales%'

sonata_user_admin_resetting:
  resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
  prefix: /{_locale}/admin/resetting
  requirements:
      _locale: '%app_locales%'
  defaults:
      _locale: '%locale%'

final_work_admin_ckeditor_image_browser:
    path: /ck/image
    defaults:
        _controller:   FinalWorkBundle:Admin\Admin:showCkImageBrowser
        _sonata_admin: "final_work.admin.article"

admin_ajax_media:
    path: /ajax/media-object-autocomplete
    defaults:
        _controller: FinalWorkBundle:Admin\AdminAjax:getMediaObjectForAutocomplete
    methods:  [GET, POST]

admin_ajax_media_list:
    path: /ajax/media-list
    defaults:
        _controller: FinalWorkBundle:Admin\AdminAjax:getMediaList
    methods:  [GET, POST]

admin_ajax_media_response:
    path: /ajax/media-response
    defaults:
        _controller: FFinalWorkBundle:Admin\AdminAjax:getMediaResponse
    methods:  [GET, POST]