api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/config/project/routing/api_platform/api_platform_task.yaml'
  formats:
    json: ['application/json']
  error_formats:
    json: ['application/json']
  swagger:
    versions: [3]
  defaults:
    normalization_context:
      skip_null_values: false
  use_symfony_listeners: true