doctrine_migrations:
  migrations_paths:
    'App\Application\Migrations': 'src/Application/Migrations'

  em: default
  storage:
    table_storage:
      table_name: 'doctrine_migration'
      version_column_name: 'version'
      version_column_length: 1024
      executed_at_column_name: 'executed_at'
      execution_time_column_name: 'execution_time'

  organize_migrations: BY_YEAR_AND_MONTH
  custom_template: ~
  all_or_nothing: false
  check_database_platform: true
