fos_elastica:
  clients:
    default:
      host: '%env(ELASTICSEARCH_HOST)%'
      port: '%env(ELASTICSEARCH_PORT)%'
      username: '%env(ELASTICSEARCH_USERNAME)%'
      password: '%env(ELASTICSEARCH_PASSWORD)%'

  indexes:
    work:
      client: default
      index_name: work_index
      properties:
        id:
          type: integer
        title:
          type: text
        shortcut:
          type: text
        deadline:
          type: date
        deadlineProgram:
          type: date
          null_value: NULL
        type:
          type: nested
          properties:
            id:
              type: integer
        status:
          type: nested
          properties:
            id:
              type: integer
        author:
          type: nested
          properties:
            id:
              type: integer
        supervisor:
          type: nested
          properties:
            id:
              type: integer
        opponent:
          type: nested
          properties:
            id:
              type: integer
        consultant:
          type: nested
          properties:
            id:
              type: integer
        created_at:
          type: date
        updated_at:
          type: date
      persistence:
        driver: orm
        model: App\Domain\Work\Entity\Work
        finder: ~
        provider: ~
        listener: ~

    conversation:
      client: default
      index_name: conversation_index
      settings:
        index:
          analysis:
            analyzer:
              lowercase_shingle_analyzer:
                type: custom
                tokenizer: standard
                filter:
                  - lowercase
                  - shingle_filter
            filter:
              shingle_filter:
                type: shingle
                min_shingle_size: 2
                max_shingle_size: 4
                output_unigrams: true
      properties:
        id:
          type: integer
        name:
          type: text
          analyzer: lowercase_shingle_analyzer
        work:
          type: nested
          properties:
            id:
              type: integer
            title:
              type: text
              analyzer: lowercase_shingle_analyzer
        messages:
          type: nested
          properties:
            id:
              type: integer
            content:
              type: text
              analyzer: lowercase_shingle_analyzer
        participants:
          type: nested
          properties:
            id:
              type: integer
            user:
              type: nested
              properties:
                id:
                  type: integer
        created_at:
          type: date
        updated_at:
          type: date
      persistence:
        driver: orm
        model: App\Domain\Conversation\Entity\Conversation
        finder: ~
        provider: ~
        listener: true

    conversation_message:
      client: default
      index_name: conversation_message_index
      settings:
        index:
          analysis:
            analyzer:
              lowercase_shingle_analyzer:
                type: custom
                tokenizer: standard
                filter:
                  - lowercase
                  - shingle_filter
            filter:
              shingle_filter:
                type: shingle
                min_shingle_size: 2
                max_shingle_size: 4
                output_unigrams: true
      properties:
        id:
          type: integer
        created_at:
          type: date
        updated_at:
          type: date
      persistence:
        driver: orm
        model: App\Domain\ConversationMessage\Entity\ConversationMessage
        finder: ~
        provider: ~
        listener: true

    task:
      client: default
      index_name: task_index
      settings:
        index:
          analysis:
            analyzer:
              lowercase_shingle_analyzer:
                type: custom
                tokenizer: standard
                filter:
                  - lowercase
                  - shingle_filter
            filter:
              shingle_filter:
                type: shingle
                min_shingle_size: 2
                max_shingle_size: 4
                output_unigrams: true
      properties:
        id:
          type: integer
        name:
          type: text
          analyzer: lowercase_shingle_analyzer
        description:
          type: text
          analyzer: lowercase_shingle_analyzer
        owner:
          type: nested
          properties:
            id:
              type: integer
        created_at:
          type: date
        updated_at:
          type: date
      persistence:
        driver: orm
        model: App\Domain\Task\Entity\Task
        finder: ~
        provider: ~
        listener: true
