overblog_graphql:
  definitions:
    schema:
      doctrine:
        query: doctrine
      not_doctrine:
        query: not_doctrine
    mappings:
      auto_discover: false
      types:
        - type: graphql
          dir: '%kernel.project_dir%/config/graphql/types'
          suffix: ~