framework:
  messenger:
    failure_transport: failed

    transports:
      email_notification: "%env(MESSENGER_TRANSPORT_DSN)%"
      failed: 'doctrine://default?queue_name=failed'

    routing:
      'App\Application\Messenger\EmailNotification\EmailNotificationMessage': email_notification
