framework:
  messenger:
    default_bus: command.bus

    buses:
      command.bus: ~

      messenger.bus.default:
        middleware:
          - App\Application\OpenTelemetry\Messenger\MessengerMiddleware

    failure_transport: failed

    transports:
      sync: 'sync://'

      email_notification:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          exchange:
            name: 'exchange.email_notification'
            type: direct
          queues:
            email_notification: ~

      loggable:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          exchange:
            name: 'exchange.loggable'
            type: direct
          queues:
            loggable: ~
        retry_strategy:
          max_retries: 0

      failed: 'doctrine://default?queue_name=failed'

    routing:
      'App\Domain\EmailNotification\Messenger\EmailNotificationMessage': email_notification
      'App\Application\Messenger\Loggable\LoggableMessage': loggable

      'App\Domain\Task\Bus\Command\CreateTask\CreateTaskCommand': sync
      'App\Domain\Task\Bus\Command\EditTask\EditTaskCommand': sync
      'App\Domain\Task\Bus\Command\ChangeStatusTask\ChangeStatusTaskCommand': sync
      'App\Domain\Task\Bus\Command\CompleteTask\CompleteTaskCommand': sync
      'App\Domain\Task\Bus\Command\DeleteTask\DeleteTaskCommand': sync
      'App\Domain\Task\Bus\Command\NotifyCompleteTask\NotifyCompleteTaskCommand': sync
