old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  producers:
    loggable:
      connection: default
      exchange_options: { name: 'final_work.loggable', type: direct }

  consumers:
    loggable:
      connection: default
      exchange_options: { name: 'final_work.loggable', type: direct }
      queue_options: { name: 'final_work.loggable' }
      callback: app.rabbit_mq.consumer.loggable
