twig:
  default_path: '%kernel.project_dir%/templates'
  globals:
    default_locale: '%locale%'
    conversation_variation: "@app.conversation_variation"
    conversation_status: "@app.conversation_status"
    conversation_message: "@app.facade.conversation_message"
    system_event: "@app.facade.system_event"
    system_event_recipient: "@app.facade.system_event_recipient"
  date:
    format: 'Y-m-d H:i:s'
