<?php

$finder = (new PhpCsFixer\Finder())
    ->in([__DIR__. '/src', __DIR__ . '/tests'])
    ->exclude('var');

return (new PhpCsFixer\Config())
    ->setRules([
        'declare_strict_types' => true,
        'backtick_to_shell_exec' => true,
        'ereg_to_preg' => true,
        'mb_str_functions' => true,
        'modernize_strpos' => true,
        'no_alias_language_construct_call' => true,
        'no_mixed_echo_print' => true,
        'set_type_to_cast' => true,
        'array_syntax' => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_whitespace_before_comma_in_array' => true,
        'normalize_index_brace' => true,
        'return_to_yield_from' => true,
        'trim_array_spaces' => true,
        'whitespace_after_comma_in_array' => true,
        'attribute_empty_parentheses' => true,
        'no_trailing_comma_in_singleline' => true,
        'numeric_literal_separator' => true,
        'octal_notation' => true,
        'single_line_empty_body' => true,
        'class_reference_name_casing' => true,
        'constant_case' => true,
        'lowercase_keywords' => true,
        'magic_constant_casing' => true,
        'native_function_casing' => true,
        'native_type_declaration_casing' => true,
        'cast_spaces' => true,
        'modernize_types_casting' => true,
        'no_unset_cast' => true,
        'short_scalar_cast' => true,
        'class_attributes_separation' => [
            'elements' => [
                'method' => 'one',
                'property' => 'one',
                'trait_import' => 'none',
                'case' => 'none'
            ]
        ],
        'no_blank_lines_after_class_opening' => true,
        'self_accessor' => true,
        'single_class_element_per_statement' => true,
        'visibility_required' => true,
        'multiline_comment_opening_closing' => true,
        'no_empty_comment' => true,
        'control_structure_continuation_position' => true,
        'empty_loop_body' => true,
        'include' => true,
        'simplified_if_return' => true,
        'switch_case_space' => true,
        'function_declaration' => true,
        'implode_call' => true,
        'lambda_not_used_import' => true,
        'no_spaces_after_function_name' => true,
        'no_useless_sprintf' => true,
        'return_type_declaration' => true,
        'static_lambda' => true,
        'void_return' => true,
        'fully_qualified_strict_types' => true,
        'global_namespace_import' => true,
        'group_import' => true,
        'no_leading_import_slash' => true,
        'no_unused_imports' => true,
        'single_line_after_imports' => true,
        'dir_constant' => true,
        'nullable_type_declaration' => true,
        'single_space_around_construct' => true,
        'blank_line_after_namespace' => true,
        'blank_lines_before_namespace' => true,
        'no_leading_namespace_whitespace' => true,
        'assign_null_coalescing_to_coalesce_equal' => true,
        'binary_operator_spaces' => true,
        'concat_space' => ['spacing' => 'one'],
        'logical_operators' => true,
        'long_to_shorthand_operator' => true,
        'new_with_parentheses' => ['named_class' => false],
        'no_space_around_double_colon' => true,
        'no_useless_concat_operator' => true,
        'no_useless_nullsafe_operator' => true,
        'object_operator_without_whitespace' => true,
        'standardize_not_equals' => true,
        'ternary_operator_spaces' => true,
        'ternary_to_elvis_operator' => true,
        'unary_operator_spaces' => true,
        'multiline_whitespace_before_semicolons' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'array_indentation' => true,
        'blank_line_before_statement' => true,
        'compact_nullable_type_declaration' => true,
        'no_spaces_around_offset' => true,
        'single_blank_line_at_eof' => true,
        'php_unit_assert_new_names' => true,
        'php_unit_attributes' => true,
        'php_unit_construct' => true,
        'php_unit_data_provider_name' => true,
        'php_unit_dedicate_assert' => true,
        'php_unit_dedicate_assert_internal_type' => true,
        'php_unit_expectation' => true,
        'php_unit_mock_short_will_return' => true,
        'php_unit_set_up_tear_down_visibility' => true,
    ])
    ->setFinder($finder)
    ->setUsingCache(false);
