version: '2.4'

services:
  redis:
    build: docker/redis
    ports:
      - "6380:6379"
  elasticsearch:
    build: docker/elasticsearch
    restart: always
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - discovery.type=single-node
    mem_limit: 1g
  rabbitmq:
    build: docker/rabbitmq
    ports:
      - "5673:5672"
  mysql:
    build: docker/mysql
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mysql/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      #      - "./docker/mysql/data:/var/lib/mysql/"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=1"
      - "MYSQL_ROOT_PASSWORD="
      - "MYSQL_DATABASE=final_work_system"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD="
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    expose:
      - '9000'
    volumes:
      - "./:/var/www/html/app"
      - "/var/www/html/app/var"
      - "/var/www/html/app/vendor"
      - "/var/www/html/app/node_modules"
      - "./docker/php/conf/php-fpm.conf:/etc/php-fpm.conf"
      - "./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/100-php.ini"
    working_dir: /var/www/html/app
    depends_on:
      - redis
      - mysql
      - rabbitmq
      - elasticsearch
    mem_limit: 1g
  mercure:
    build: docker/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
    ports:
      - '8656:80'
