version: '2.3'

services:
  redis:
    build: docker/redis
  mariadb:
    build: docker/mysql
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mysql/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=final_work_system"
      - "MYSQL_USER=final_work_system"
      - "MYSQL_PASSWORD=password"
  php:
    build: docker/php
    volumes:
      - "./:/var/www/html/app"
      - "./docker/php/conf/php-fpm.conf:/etc/php-fpm.conf"
      - "./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/100-php.ini"
    depends_on:
      - mariadb
  nginx:
    build: docker/nginx
    ports:
      - "9090:80"
    volumes:
      - "./:/var/www/html/app"
      - './docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
  node:
    build: docker/node
    volumes:
      - "./:/var/www/html/app"