services:
    extension.listener:
        class: FinalWork\FinalWorkBundle\EventListener\DoctrineExtensionListener
        arguments:
            - '@security.helper'
        calls:
            - [ setContainer, [ "@service_container" ] ]
        tags:
            # loggable hooks user username if one is in security context
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }