# User routing
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

fos_user_security_login:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:Security:login
  path: /{_locale}/login
  requirements:
    _locale: '%app_locales%'
  methods:  [GET, POST]

fos_user_security_check:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:Security:check
  path: /{_locale}/login_check
  requirements:
    _locale: '%app_locales%'
  methods:  [POST]

fos_user_security_logout:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:Security:logout
  path: /{_locale}/logout
  requirements:
    _locale: '%app_locales%'
  methods:  [GET, POST]

fos_user_profile_show:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:Profile:show
  path: /{_locale}/profile/
  requirements:
    _locale: '%app_locales%'

fos_user_profile_edit:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:Profile:edit
  path: /{_locale}/profile/edit
  requirements:
    _locale: '%app_locales%'

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /{_locale}/register
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

fos_user_resetting_request:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:Resetting:request
  path: /{_locale}/resetting/request
  requirements:
    _locale: '%app_locales%'
  methods:  [GET]

fos_user_resetting_send_email:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:Resetting:sendEmail
  path: /{_locale}/resetting/send-email
  requirements:
    _locale: '%app_locales%'
  methods:  [POST]

fos_user_resetting_check_email:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:Resetting:checkEmail
  path: /{_locale}/resetting/check-email
  requirements:
    _locale: '%app_locales%'
  methods:  [GET]

fos_user_resetting_reset:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:Resetting:reset
  path: /{_locale}/resetting/reset/{token}
  requirements:
    _locale: '%app_locales%'
  methods:  [GET, POST]

fos_user_change_password:
  defaults:
    _locale: '%locale%'
    _controller: FinalWorkUserBundle:ChangePassword:changePassword
  path: /{_locale}/profile/change-password
  requirements:
    _locale: '%app_locales%'
