parameters:
  api_key_field:
    parameters:
      date_format: 'Y-m-d H:i:s'

    Work:
      fields:
        - id
        - title
        - type
        - status
        - deadline
        - deadlineProgram
        - author
        - supervisor
        - opponent
        - consultant
    User:
      fields:
        - id
        - username
        - firstname
        - lastname
        - fullName
        - degreeBefore
        - degreeAfter
        - email
        - roles
    WorkType:
      fields:
        - id
        - name
        - description
    WorkStatus:
      fields:
        - id
        - name
        - description
    Task:
      fields:
        - id
        - name
        - description
        - complete:
            parameters:
              method: 'isComplete'
        - notifyComplete:
            parameters:
              method: 'isNotifyComplete'
        - owner
        - work
        - deadline
    Event:
      fields:
        - id
        - type
        - name
        - start
        - end
        - comment
        - participant
    Comment:
      fields:
        - id
        - content
        - owner
    EventType:
      fields:
        - id
        - name
        - description
    EventAddress:
      fields:
        - id
        - name
        - description
        - street
        - skype
        - latitude
        - longitude
        - owner
    EventParticipant:
      fields:
        - id
        - firstName
        - secondName
        - email
        - user
        - work
