parameters:
  conversation:
    variation:
      author:
        author: false
        supervisor: true
        opponent: false
        consultant: false
      opponent:
        author: false
        supervisor: true
        opponent: false
        consultant: false
      supervisor:
        author: true
        supervisor: false
        opponent: true
        consultant: true
      consultant:
        author: false
        consultant: false
        opponent: false
        supervisor: true
