# Assetic Configuration
assetic:
  debug:                '%kernel.debug%'
  use_controller:       '%kernel.debug%'
  write_to:             '%kernel.project_dir%/web/compiled/'
  filters:
    cssrewrite: ~
    jsqueeze: ~
    scssphp:
      formatter: 'Leafo\ScssPhp\Formatter\Compressed'
  bundles:
    - FinalWorkBundle
    - FinalWorkUserBundle
    - TwigBundle
    - FOSUserBundle