imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: security.yml }
    - { resource: doctrine/*}
    - { resource: redis.yaml }
    - { resource: fos.yaml }
    - { resource: twig.yaml }
    - { resource: knp.yaml }
    - { resource: roukmoute.yaml }
    - { resource: assetic.yaml }
    - { resource: sonata/* }
    - { resource: swiftmailer.yaml }
    - { resource: graphql/graphql.yaml }
    - { resource: ivory/ivory_ckeditor.yml }

parameters:
    system_info:
        name: 'FinalWork System'
        version: '1.0.0'
    app_locales: en|cs|ru
    locale: cs
    sonata.user.admin.user.class: FinalWork\SonataUserBundle\Admin\UserAdmin
    upload_directory: '%kernel.project_dir%/web/upload/'
    email_notification_subscriber:
        sender: null
        enable: false
        translator_domain: 'email_notification'
        default_locale: '%locale%'
        google_analytics_code: null
    google_maps_key: null
    google_analytics_code: 'UA'
    template:
        ajax: 'ajax/'
    pagination:
        default:
            page: 1
            limit: 25
        home:
            limit: 100
        work:
            deadline_limit: 10
            program_deadline_limit: 10
        conversation:
            message_list: 10
        document_category:
            limit: 50
        task:
            deadline_limit: 10
        work_detail_tab:
            task:
                page: 1
                limit: 15
            version:
                page: 1
                limit: 10
            event:
                page: 1
                limit: 10
            message:
                page: 1
                limit: 15
framework:
    esi: { enabled: true }
    translator: { fallbacks: ['%locale%'] }
    default_locale: '%locale%'
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: true
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    trusted_hosts: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name: SFSESSID
        cookie_lifetime: 86400
        gc_maxlifetime: 86400
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true