# Swiftmailer Configuration
swiftmailer:
  transport:    '%mailer_transport%'
  host:         '%mailer_host%'
  username:     '%mailer_user%'
  password:     '%mailer_password%'
  spool:        { type: memory }

#    auth_mode:    '%mailer_auth_mode%'
#    encryption:   '%mailer_encryption%'
#    port:         '%mailer_port%'