# Sonata Configuration
sonata_block:
  default_contexts: [cms]
  blocks:
    # Enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts:  [admin]
    sonata.user.block.menu:  # used to display the menu in profile pages
    sonata.user.block.account: # used to display menu option (login option)
    sonata.block.service.text: # used to if you plan to use Sonata user routes

# Sonata Configuration
sonata_user:
  #security_acl: true # Uncomment for ACL support
  manager_type: orm # can be orm or mongodb
  class:
    user: 'FinalWork\SonataUserBundle\Entity\User'
    group: 'FinalWork\SonataUserBundle\Entity\Group'
  impersonating:
    route: homepage

# Sonata Configuration
sonata_admin:
  security:
    handler: sonata.admin.security.handler.role
    information:
      GUEST:    [VIEW, LIST]
      STAFF:    [EDIT, LIST, CREATE]
      EDITOR:   [OPERATOR, EXPORT]
      ADMIN:    [MASTER]
    # permissions not related to an object instance and also to be available when objects do not exist
    # the DELETE admin permission means the user is allowed to batch delete objects
    admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
    # permission related to the objects
    object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]