ivory_ck_editor:
    default_config: default
    input_sync: true
    configs:
        default:
            extraPlugins: 'autogrow'
            # Nastavení, aby CKEditor neodstraňoval nadbytečné elementy
            allowedContent: true
            toolbar:
                - [Preview]
                - [Undo, Redo]
                - [Copy, Paste, PasteText, PasteFromWord]
                - [Format, Bold, Italic]
                - [NumberedList, BulletedList, Indent, Outdent, Table ,JustifyLeft, JustifyCenter, JustifyRight, JustifyBlock]
                - [Image, Link, Unlink, SpecialChar]
                - [Source, Maximize]

            filebrowserImageBrowseRoute: final_work_admin_ckeditor_image_browser
    plugins:
        autogrow:
            path: '/bundles/sonataformatter/vendor/ckeditor/plugins/autogrow/'
            filename: 'plugin.js'