receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: "http://apm-server:8200"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp, debug]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp, debug]
    logs:
      receivers: [otlp]
      exporters: [otlphttp, debug]
