api_key_event_work_list:
  path: /works/{id}
  requirements:
    id: '\d+'
  defaults:
    _controller: App\Domain\Event\Controller\Api\EventController::list
  methods: [GET, POST]

api_key_delete_event:
  path: /{id}
  requirements:
    id: '\d+'
  defaults:
    _controller: App\Domain\Event\Controller\Api\EventController::delete
  methods: [DELETE]

api_key_get_event:
  path: /{id}
  requirements:
    id: '\d+'
  defaults:
    _controller: App\Domain\Event\Controller\Api\EventController::detail
  methods: [GET]
