api_key_conversations:
  path: /
  defaults:
    _controller: App\Domain\Conversation\Controller\Api\ConversationController::list
  methods: [GET]

api_key_conversation_detail:
  path: /{id}
  requirements:
    id: '\d+'
  defaults:
    _controller: App\Domain\Conversation\Controller\Api\ConversationController::detail
  methods: [GET]

api_key_conversation_messages:
  path: /{id}/messages
  requirements:
    id: '\d+'
  defaults:
    _controller: App\Domain\Conversation\Controller\Api\ConversationController::messages
  methods: [GET]

api_key_conversation_message_create:
  path: /{id}/message
  requirements:
    id: '\d+'
  defaults:
    _controller: App\Domain\Conversation\Controller\Api\ConversationController::createMessage
  methods: [POST]

api_key_conversation_work_messages:
  path: /works/{id}/messages
  requirements:
    id: '\d+'
  defaults:
    _controller: App\Domain\Conversation\Controller\Api\ConversationController::listWorkMessage
  methods: [GET, POST]

api_key_conversation_message_change_read_status:
  path: /{id_conversation}/messages/{id_message}/change/read/status
  requirements:
    id_conversation: '\d+'
    id_message: '\d+'
  defaults:
    _controller: App\Domain\Conversation\Controller\Api\ConversationController::changeMessageReadStatus
  methods: [PUT]

api_key_conversation_message_change_all_to_read:
  path: /messages/change-all-to-read
  defaults:
    _controller: App\Domain\Conversation\Controller\Api\ConversationController::allMessageToRead
  methods: [PUT]
