api_key_work_list:
  path: /{type}/list
  requirements:
    type: 'author|opponent|consultant|unused'
  defaults:
    _controller: App\Domain\Work\Controller\Api\WorkController::list
  methods: [GET, POST]
