api_key_get_event_calendar:
  path: /{type}
  requirements:
    type: "manage|reservation|detail"
  defaults:
    _controller: App\Domain\EventCalendar\Controller\Api\EventCalendarController::getEvent
  methods: [GET]

api_key_get_event_calendar_user_work:
  path: /reservation/user/works
  defaults:
    _controller: App\Domain\EventCalendar\Controller\Api\EventCalendarController::getUserReservationWorks
  methods: [GET]
