api_key_work_list:
  path: /{type}
  requirements:
    type: 'author|opponent|consultant|supervisor'
  defaults:
    _controller: App\Domain\Work\Controller\Api\WorkController::list
  methods: [GET, POST]

api_key_work_detail:
  path: /{id}/detail
  requirements:
    id: '\d+'
  defaults:
    _controller: App\Domain\Work\Controller\Api\WorkController::detail
  methods: [GET, POST]
