api_key_get_task_detail:
  path: /{id_task}/works/{id_work}
  requirements:
    id_task: '\d+'
    id_work: '\d+'
  defaults:
    _controller: App\Domain\Task\Controller\Api\TaskController::detail
  methods: [GET]
