api_key_task_list_owner:
  path: /list-owner
  defaults:
    _controller: App\Domain\Task\Controller\Api\TaskController::listOwner
  methods: [GET, POST]

api_key_task_list_solver:
  path: /list-solver
  defaults:
    _controller: App\Domain\Task\Controller\Api\TaskController::listSolver
  methods: [GET, POST]
