api_key_conversation_message_work_list:
  path: /work/{id}/message/list
  requirements:
    id: '\d+'
  defaults:
    _controller: App\Domain\Conversation\Controller\Api\ConversationController::listWorkMessage
  methods: [GET, POST]
