api_key_get_user_info:
  path: /detail
  defaults:
    _controller: App\Domain\User\Controller\Api\UserController::detail
  methods: [GET]

api_key_get_user_list:
  path: /{type}
  requirements:
    type: 'author|opponent|consultant|unused'
  defaults:
    _controller: App\Domain\User\Controller\Api\UserController::list
  methods: [GET]

api_key_get_user_profile_image:
  path: /{id}/profile/image
  defaults:
    _controller: App\Domain\Profile\Controller\Api\ProfileController::image
  methods: [GET]
