parameters:
  api_fields:
    default:
      Work:
        - 'id'
        - 'title'
        - 'type'
        - 'status'
        - 'deadline'
        - 'deadlineProgram'
        - 'author'
        - 'supervisor'
        - 'opponent'
        - 'consultant'
      User:
        - 'id'
        - 'username'
        - 'firstName'
        - 'lastName'
        - 'degreeBefore'
        - 'degreeAfter'
        - 'messageGreeting'
        - 'messageSignature'
      WorkType:
        - 'id'
        - 'name'
        - 'description'
      WorkStatus:
        - 'id'
        - 'name'
        - 'description'