conversation_list:
  path:     /list
  defaults:
      _controller: FinalWorkBundle:Conversation:list
  methods:  [GET, POST]

conversation_detail:
  path: /detail/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
     _controller: FinalWorkBundle:Conversation:detail
  methods:  [GET, POST]

conversation_create:
  path: /create
  defaults:
     _controller: FinalWorkBundle:Conversation:create
  methods:  [GET, POST]

conversation_work_create:
  path: /create/work/{id_work}/user/{id_user_one}/user/{id_user_two}
  requirements:
      id_work: "^[a-zA-Z0-9]{10}$"
      id_user_one: "^[a-zA-Z0-9]{10}$"
      id_user_two: "^[a-zA-Z0-9]{10}$"
  defaults:
     _controller: FinalWorkBundle:Conversation:createWorkConversation
  methods:  [GET, POST]

conversation_message_change_read_status_ajax:
  path: /message/{id}/change/read/status/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\Conversation:changeReadMessageStatus
  methods:  [POST]

conversation_message_last:
  path: /{id}/last/message
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Conversation:lastMessage
  methods:  [GET, POST]