document_create:
  path: /create
  defaults:
      _controller: FinalWorkBundle:Document:create
  methods:  [GET, POST]

document_create_ajax:
  path: /create/ajax
  defaults:
      _controller: FinalWorkBundle:Ajax\Document:create
  methods:  [POST]

document_edit:
  path: /edit/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Document:edit
  methods:  [GET, POST]

document_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\Document:edit
  methods:  [GET, POST]

document_list:
  path: /list
  defaults:
      _controller: FinalWorkBundle:Document:list
  methods:  [GET, POST]

document_list_owner:
  path: /list/owner
  defaults:
      _controller: FinalWorkBundle:Document:listOwner
  methods:  [GET, POST]

document_change_active_ajax:
  path: /change/{id}/active/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\Document:changeActive
  methods:  [POST]

document_download:
  path: /download/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Document:download
  methods:  [GET,POST]

document_google_download:
  path: /google/download/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Document:download
  methods:  [GET,POST]

document_delete_ajax:
  path: /document/delete/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\Document:delete
  methods:  [POST, DELETE]

