document_category_create:
  path: /create
  defaults:
      _controller: FinalWorkBundle:DocumentCategory:create
  methods:  [GET, POST]

document_category_create_ajax:
  path: /create/ajax
  defaults:
      _controller: FinalWorkBundle:Ajax\DocumentCategory:create
  methods:  [POST]

document_category_edit:
  path: /edit/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:DocumentCategory:edit
  methods:  [GET, POST]

document_category_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\DocumentCategory:edit
  methods:  [POST]

document_category_list:
  path: /list
  defaults:
      _controller: FinalWorkBundle:DocumentCategory:list
  methods:  [GET, POST]

document_category_delete:
  path: /delete/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:DocumentCategory:delete
  methods:  [POST, DELETE]

document_category_delete_ajax:
  path: /delete/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\DocumentCategory:delete
  methods:  [POST, DELETE]
