event_detail:
  path:     /detail/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
    _controller: FinalWorkBundle:Event:detail
  methods:  [GET,POST]

event_edit:
  path:     /edit/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
    _controller: FinalWorkBundle:Event:edit
  methods:  [GET,POST]

event_edit_ajax:
  path:     /edit/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
    _controller: FinalWorkBundle:Ajax\Event:edit
  methods:  [POST]

event_switch_to_skype:
  path:     /switch-skype/{id}
  defaults:
    _controller: FinalWorkBundle:Event:switchToSkype
  methods:  [GET,POST]

event_delete:
  path: /delete/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Event:delete
  methods:  [DELETE]

event_delete_ajax:
  path: /delete/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\Event:delete
  methods:  [GET, POST]

event_detail_events_ajax:
  path: /detail/{id}/calendar/events/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\Event:getEvent
  methods:  [POST]
