event_address_list:
  path:     /list
  defaults:
    _controller: FinalWorkBundle:EventAddress:list
  methods:  GET

event_address_detail:
  path:     /detail/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
    _controller: FinalWorkBundle:EventAddress:detail
  methods:  GET

event_address_create:
  path:      /create
  defaults:
    _controller: FinalWorkBundle:EventAddress:create
  methods:  [GET, POST]

event_address_create_ajax:
   path:      /create/ajax
   defaults:
     _controller: FinalWorkBundle:Ajax\EventAddress:create
   methods:  [POST]

event_address_edit:
  path:     /edit/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
    _controller: FinalWorkBundle:EventAddress:edit
  methods:  [GET, POST]

event_address_edit_ajax:
  path:     /edit/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
    _controller: FinalWorkBundle:Ajax\EventAddress:edit
  methods:  [POST]

event_address_delete:
  path:     /delete/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
    _controller: FinalWorkBundle:EventAddress:delete
  methods:  DELETE

event_address_delete_ajax:
  path:     /delete/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
    _controller: FinalWorkBundle:Ajax\EventAddress:delete
  methods:  [POST]
