event_calendar_reservation:
    path: /reservation
    defaults:
      _controller: FinalWorkBundle:EventCalendar:reservation
    methods:  [GET]

event_calendar_manage:
    path: /manage
    defaults:
      _controller: FinalWorkBundle:EventCalendar:manage
    methods:  [GET]

event_calendar_create_ajax:
  path: /create/ajax
  defaults:
      _controller: FinalWorkBundle:Ajax\EventCalendar:create
  methods:  [POST]

event_calendar_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
    id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\EventCalendar:edit
  methods:  [POST]

event_calendar_reservation_ajax:
  path: /reservation/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
    _controller: FinalWorkBundle:Ajax\EventCalendar:eventReservation
  methods:  [POST]

event_calendar_events_ajax:
  path: /events/{type}/ajax
  requirements:
      type: "manage|reservation|detail"
  defaults:
      _controller: FinalWorkBundle:Ajax\EventCalendar:getEvent
  methods:  [POST]
