work_category_create:
  path: /create
  defaults:
      _controller: FinalWorkBundle:WorkCategory:create
  methods:  [GET, POST]

work_category_create_ajax:
  path: /create/ajax
  defaults:
      _controller: FinalWorkBundle:Ajax\WorkCategory:create
  methods:  [POST]

work_category_edit:
  path: /edit/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:WorkCategory:edit
  methods:  [GET, POST]

work_category_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\WorkCategory:edit
  methods:  [POST]

work_category_list:
  path: /list
  defaults:
      _controller: FinalWorkBundle:WorkCategory:list
  methods:  [GET, POST]

work_category_delete:
  path: /delete/{id}
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:WorkCategory:delete
  methods:  [POST, DELETE]

work_category_delete_ajax:
  path: /delete/{id}/ajax
  requirements:
      id: "^[a-zA-Z0-9]{10}$"
  defaults:
      _controller: FinalWorkBundle:Ajax\WorkCategory:delete
  methods:  [POST, DELETE]
