pipelines:
  default:
    - step:
        name: phpunit
        image: docker/compose
        services:
          - docker
        caches:
          - docker
        script:
          - docker network create dockernet
          - docker-compose -f docker-compose-bitbucket-cache.yml up -d
          - docker-compose exec -T php sh bin/composer-first-install.sh
          - docker-compose exec -T php composer phpunit
    - step:
        name: cypress
        image: docker/compose
        size: 2x
        services:
          - docker
        caches:
          - docker
        script:
          - docker network create dockernet
          - docker-compose -f docker-compose.yml up -d
          - docker-compose exec -T php sh bin/composer-first-install.sh
          - docker-compose exec -T php php bin/console app:import-sql docker/mysql/data/dump.sql
          - docker-compose exec -T node sh bin/npm-first-install.sh
          - docker-compose exec -T node npm run cypress:run

definitions:
  services:
    docker:
      memory: 1800