homepage:
  path: /{_locale}
  controller: App\Application\Controller\HomeController::index
  defaults:
    _locale: '%locale%'
    _seo:
      title: 'app.page.home'
  requirements:
    _locale: '%locales%'
  methods: [GET]

app:
  resource: project/routing.yaml