imports:
  - { resource: project/parameters.yaml }
  - { resource: project/services.yaml }

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  App\Admin\:
    resource: '../src/Admin'
    public: true

  App\Controller\:
    resource: '../src/Controller'
    public: true
    tags: ['controller.service_arguments']
    calls:
      - [setContainer, ["@service_container"]]

  App\Repository\:
    resource: '../src/Repository'
    public: true

  App\Model\:
    resource: '../src/Model/*/Http'
    public: true
