imports:
  - { resource: project/parameters.yaml }
  - { resource: project/services.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $locale: '%locale%'
      $locales: '%locales%'
      $domain: '%domain%'
      $container: '@service_container'
      $systemInfo: '%system_info%'

  App\Application\:
    resource: '../src/Application'
    exclude:
      - '../src/Application/Attribute'
      - '../src/Application/Cache'
      - '../src/Application/Constant'
      - '../src/Application/DataTransferObject'
      - '../src/Application/DBAL'
      - '../src/Application/DependencyInjection'
      - '../src/Application/DTO'
      - '../src/Application/EventDispatcher/GenericEvent'
      - '../src/Application/Exception'
      - '../src/Application/GraphQL'
      - '../src/Application/Helper'
      - '../src/Application/Interfaces'
      - '../src/Application/Menu'
      - '../src/Application/Messenger/*/*Message.php'
      - '../src/Application/Migrations'
      - '../src/Application/Helper'
      - '../src/Application/Traits'
      - '../src/Application/Widget'
      - '../src/Application/Model'
      - '../src/Application/Repository/*QueryBuilder.php'

  App\Domain\:
    resource: '../src/Domain'
    exclude:
      - '../src/Domain/*/DTO/'
      - '../src/Domain/*/Entity/'
      - '../src/Domain/*/Exception'
      - '../src/Domain/*/Constant'
      - '../src/Domain/*/Model'
      - '../src/Domain/*/Repository/*QueryBuilder.php'
      - '../src/Domain/*/Security/Voter/Subject'
      - '../src/Domain/*/EventDispatcher/GenericEvent'
      - '../src/Domain/Comment/Form/EventSubscriber'
      - '../src/Domain/Widget/WidgetItem'

  App\Domain\Work\Repository\Elastica\WorkSearch:
    arguments:
      $transformedFinderWork: '@fos_elastica.finder.work'

  App\Domain\Conversation\Repository\Elastica\ConversationSearch:
    arguments:
      $transformedFinderConversation: '@fos_elastica.finder.conversation'

  App\Domain\ConversationMessage\Repository\Elastica\ConversationMessageSearch:
    arguments:
      $transformedFinderConversationMessage: '@fos_elastica.finder.conversation_message'

  App\Domain\Task\Repository\Elastica\TaskSearch:
    arguments:
      $transformedFinderTask: '@fos_elastica.finder.task'

  App\Application\EventListener\LoggableListener:
    tags:
      - { name: doctrine.event_listener, event: 'onFlush' }
      - { name: doctrine.event_listener, event: 'loadClassMetadata' }
      - { name: doctrine.event_listener, event: 'postPersist' }

  App\Domain\SystemEvent\Cache\HomepageCache:
    arguments:
      $cache: '@cache.app'
