imports:
  - { resource: project/parameters.yaml }
  - { resource: project/services.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $locale: '%locale%'
      $locales: '%locales%'
      $domain: '%domain%'
      $container: '@service_container'
      $systemInfo: '%system_info%'

  App\Infrastructure\:
    resource: '../src/Infrastructure'
    exclude:
      - '../src/Infrastructure/Config/DependencyInjection'
      - '../src/Infrastructure/Persistence/Doctrine'
      - '../src/Infrastructure/GraphQL'
      - '../src/Infrastructure/OpenTelemetry/*/Context'
      - '../src/Infrastructure/OpenTelemetry/Helper'
      - '../src/Infrastructure/Messaging/*/*Message.php'

  App\Application\:
    resource: '../src/Application'
    exclude:
      - '../src/Application/Attribute'
      - '../src/Application/Cache'
      - '../src/Application/Constant'
      - '../src/Application/DataTransferObject'
      - '../src/Application/DTO'
      - '../src/Application/EventDispatcher/GenericEvent'
      - '../src/Application/Exception'
      - '../src/Application/Helper'
      - '../src/Application/Mapper/Attribute'
      - '../src/Application/Menu'
      - '../src/Application/Migrations'
      - '../src/Application/Model'
      - '../src/Application/Helper'
      - '../src/Application/Traits'
      - '../src/Application/Widget'
      - '../src/Application/Model'
      - '../src/Application/Repository/*QueryBuilder.php'

  App\Domain\:
    resource: '../src/Domain'
    exclude:
      - '../src/Domain/*/Bus/Query/*/*QueryResult.php'
      - '../src/Domain/*/DataTransferObject/'
      - '../src/Domain/*/DTO/'
      - '../src/Domain/*/Entity/'
      - '../src/Domain/*/Exception'
      - '../src/Domain/*/Constant'
      - '../src/Domain/*/Model'
      - '../src/Domain/*/Helper'
      - '../src/Domain/*/Traits'
      - '../src/Domain/*/Repository/*QueryBuilder.php'
      - '../src/Domain/*/Security/Voter/Subject'
      - '../src/Domain/*/EventDispatcher/GenericEvent'
      - '../src/Domain/Comment/Form/EventSubscriber'
      - '../src/Domain/Widget/WidgetItem'
      - '../src/Domain/EmailNotification/Messenger/EmailNotificationMessage.php'

  App\Domain\Work\Repository\Elastica\WorkSearch:
    arguments:
      $transformedFinderWork: '@fos_elastica.finder.work'

  App\Domain\Conversation\Repository\Elastica\ConversationSearch:
    arguments:
      $transformedFinderConversation: '@fos_elastica.finder.conversation'

  App\Domain\ConversationMessage\Repository\Elastica\ConversationMessageSearch:
    arguments:
      $transformedFinderConversationMessage: '@fos_elastica.finder.conversation_message'

  App\Domain\Task\Repository\Elastica\TaskSearch:
    arguments:
      $transformedFinderTask: '@fos_elastica.finder.task'

  App\Infrastructure\Event\EventListener\LoggableListener:
    tags:
      - { name: doctrine.event_listener, event: 'onFlush' }
      - { name: doctrine.event_listener, event: 'loadClassMetadata' }
      - { name: doctrine.event_listener, event: 'postPersist' }

  App\Domain\SystemEvent\Cache\HomepageCache:
    arguments:
      $cache: '@cache.app'

  _instanceof:
    App\Application\Interfaces\Bus\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    App\Application\Interfaces\Bus\QueryHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: query.bus }
