# GraphQl
overblog_graphql:
  definitions:
    schema:
      doctrine:
        query: doctrine
        resolver_maps:
          - "final_work.graph_ql.resolver.user"
          - "final_work.graph_ql.resolver.task"
          - "final_work.graph_ql.resolver.work"
      not_doctrine:
        query: not_doctrine
        resolver_maps:
          - "final_work.graph_ql.resolver.not_doctrine"
    mappings:
      auto_discover: false
      types:
        - type: graphql
          dir: "%kernel.project_dir%/app/config/graphql/types"
          suffix: ~