imports:
  - { resource: api/* }
  - { resource: conversation/* }
  - { resource: services/* }
  - { resource: menu.yaml }
  - { resource: widget.yaml }

parameters:
  container.build_id: "a fake build id"
  domain: '%env(PROJECT_DOMAIN)%'
  system_info:
    name: 'FinalWork System'
    version: '3.7.0'
  locales: 'en|cs|ru'
  locale: 'cs'
  upload_directory: '%kernel.project_dir%/public/upload/'
  email_notification:
    sender: '%env(EMAIL_NOTIFICATION_SENDER)%'
    enable_send: '%env(bool:EMAIL_NOTIFICATION_ENABLE_SEND)%'
    enable_rabbit_mq: '%env(bool:EMAIL_NOTIFICATION_ENABLE_RABBIT_MQ)%'
    enable_add_to_queue: '%env(bool:EMAIL_NOTIFICATION_ENABLE_ADD_TO_QUEUE)%'
    translator_domain: 'email_notification'
    default_locale: '%locale%'
  task_remind:
    enable: '%env(bool:TASK_REMIND_ENABLE)%'
    translator_domain: 'email_notification'
    default_locale: '%locale%'
  google_maps_key: '%env(GOOGLE_MAPS_KEY)%'
  google_analytics_code: '%env(GOOGLE_ANALYTICS_CODE)%'
  template:
    ajax: 'ajax/'
  pagination:
    default:
      page: 1
      limit: 25
    home:
      limit: 100
    work:
      deadline_limit: 10
      program_deadline_limit: 10
    conversation:
      message_list: 10
    document_category:
      limit: 50
    task:
      deadline_limit: 10
    work_detail_tab:
      task:
        page: 1
        limit: 15
      version:
        page: 1
        limit: 10
      event:
        page: 1
        limit: 10
      message:
        page: 1
        limit: 15
  hashid: '^[a-zA-Z0-9]{10}$'
  default_user_image: 'images/user.png'
  event_calendar:
    reserved_color: '#f00'
    detail_reserved_color: '#4bd44d'
  constraints:
    profile:
      file:
        maxSize: '500k'
        mimeTypes: [ 'image/jpeg', 'image/png' ]
      image:
        minWidth: 200
        maxWidth: 1200
        minHeight: 200
        maxHeight: 1200
  homepage_notify:
    type_class:
      info: 'alert-info'
      danger: 'alert-danger'
      success: 'alert-success'
      warning: 'alert-warning'
    notifies:
      - 'app.widget.user_profile_information'
      - 'app.widget.work_deadline_information'
  reset_password:
    cryptographically_secure_key: '45679'
    reset_request_lifetime: 3600
    request_throttle_time: 3600
  event_source:
    conversation:
      detail:
        active: true
        sleep: 60
    widget:
      top_nav:
        active: true
        sleep: 60
  cache:
    homepage_time: 86400
