czech:
  'A': 'A'
  'Á': 'AZ'
  'B': 'B'
  'C': 'C'
  'Č': 'CZ'
  'D': 'D'
  'Ď': 'DZ'
  'E': 'E'
  'É': 'EZ'
  'Ě': 'EZZ'
  'F': 'F'
  'G': 'G'
  'H': 'H'
  'I': 'I'
  'Í': 'IZ'
  'J': 'J'
  'K': 'K'
  'L': 'L'
  'M': 'M'
  'N': 'N'
  'Ň': 'NZ'
  'O': 'O'
  'Ó': 'OZ'
  'P': 'P'
  'Q': 'Q'
  'R': 'R'
  'Ř': 'RZ'
  'S': 'S'
  'Š': 'SZ'
  'T': 'T'
  'Ť': 'TZ'
  'U': 'U'
  'Ú': 'UZ'
  'Ů': 'UZZ'
  'V': 'V'
  'W': 'W'
  'X': 'X'
  'Y': 'Y'
  'Ý': 'YZ'
  'Z': 'Z'
  'Ž': 'ZZ'
  'a': 'a'
  'á': 'az'
  'b': 'b'
  'c': 'c'
  'č': 'cz'
  'd': 'd'
  'ď': 'dz'
  'e': 'e'
  'é': 'ez'
  'ě': 'ezz'
  'f': 'f'
  'g': 'g'
  'h': 'h'
  'i': 'i'
  'í': 'iz'
  'j': 'j'
  'k': 'k'
  'l': 'l'
  'm': 'm'
  'n': 'n'
  'ň': 'nz'
  'o': 'o'
  'ó': 'oz'
  'p': 'p'
  'q': 'q'
  'r': 'r'
  'ř': 'rz'
  's': 's'
  'š': 'sz'
  't': 't'
  'ť': 'tz'
  'u': 'u'
  'ú': 'uz'
  'ů': 'uzz'
  'v': 'v'
  'w': 'w'
  'x': 'x'
  'y': 'y'
  'ý': 'yz'
  'z': 'z'
  'ž': 'zz'