name:  View log files
description:  View log files

runs:
  using: 'composite'
  steps:
    - name:  View log files
      shell: bash
      run: |
        docker-compose exec -T php cat var/log/prod.log || true
        docker-compose exec -T php cat var/log/dev.log || true
