services:
  #  Controller
  final_work.controller.version:
    class: FinalWork\FinalWorkBundle\Controller\VersionController
    calls:
      - [setContainer, ["@service_container"]]

  final_work.controller.document:
    class: FinalWork\FinalWorkBundle\Controller\DocumentController
    calls:
      - [setContainer, ["@service_container"]]