services:
  #  DataGrid
  final_work.data_grid.user:
    class: FinalWork\FinalWorkBundle\DataGrid\UserDataGrid
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.data_grid.work_category:
    class: FinalWork\FinalWorkBundle\DataGrid\WorkCategoryDataGrid
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.data_grid.media_category:
    class: FinalWork\FinalWorkBundle\DataGrid\MediaCategoryDataGrid
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.data_grid.work_status:
    class: FinalWork\FinalWorkBundle\DataGrid\WorkStatusDataGrid
    arguments:
      - '@doctrine.orm.entity_manager'