services:
  final_work.facade.api.user:
    class: FinalWork\FinalWorkBundle\Model\ApiUser\ApiUserFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.article_category:
    class: FinalWork\FinalWorkBundle\Model\Article\ArticleCategoryFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.article:
    class: FinalWork\FinalWorkBundle\Model\Article\ArticleFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.comment:
    class: FinalWork\FinalWorkBundle\Model\Comment\CommentFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.conversation:
    class: FinalWork\FinalWorkBundle\Model\Conversation\ConversationFacade
    arguments:
      - '@doctrine.orm.entity_manager'
      - "@final_work.facade.conversation_message"
      - "@final_work.facade.conversation_status"
      - "@final_work.conversation_variation"
      - "@final_work.event_dispatcher.conversation"
      - "@final_work.factory.conversation"

  final_work.facade.event_address:
    class: FinalWork\FinalWorkBundle\Model\EventAddress\EventAddressFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.event_calendar:
    class: FinalWork\FinalWorkBundle\Model\Event\EventCalendarFacade
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@router'
      - '@hashids'

  final_work.facade.event_participant:
    class: FinalWork\FinalWorkBundle\Model\Event\EventParticipantFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.event_schedule:
    class: FinalWork\FinalWorkBundle\Model\EventSchedule\EventScheduleFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.media_category:
    class: FinalWork\FinalWorkBundle\Model\Media\MediaCategoryFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.media.mime_type:
    class: FinalWork\FinalWorkBundle\Model\Media\MediaMimeTypeFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.media:
    class: FinalWork\FinalWorkBundle\Model\Media\MediaFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.media_type:
    class: FinalWork\FinalWorkBundle\Model\Media\MediaTypeFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.system_event_recipient:
    class: FinalWork\FinalWorkBundle\Model\SystemEvent\SystemEventRecipientFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.system_event:
    class: FinalWork\FinalWorkBundle\Model\SystemEvent\SystemEventFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.task_deadline:
    class: FinalWork\FinalWorkBundle\Model\Task\TaskDeadlineFacade
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@final_work.parameters'

  final_work.facade.task:
    class: FinalWork\FinalWorkBundle\Model\Task\TaskFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.user_group:
    class: FinalWork\FinalWorkBundle\Model\UserGroup\UserGroupFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.user:
    class: FinalWork\FinalWorkBundle\Model\User\UserFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.work.category:
    class: FinalWork\FinalWorkBundle\Model\WorkCategory\WorkCategoryFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.work.deadline:
    class: FinalWork\FinalWorkBundle\Model\WorkDeadline\WorkDeadlineFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.work:
    class: FinalWork\FinalWorkBundle\Model\Work\WorkFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.work_status:
    class: FinalWork\FinalWorkBundle\Model\WorkStatus\WorkStatusFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.event:
    class: FinalWork\FinalWorkBundle\Model\Event\EventFacade
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.facade.conversation_message:
    class: FinalWork\FinalWorkBundle\Model\Conversation\ConversationMessageFacade
    arguments:
      - '@doctrine.orm.entity_manager'
      - "@final_work.facade.conversation_status"