services:
  final_work.factory.conversation:
    class: FinalWork\FinalWorkBundle\Model\Conversation\ConversationFactory
    arguments:
      - '@doctrine.orm.entity_manager'
      - "@final_work.facade.conversation_message"
      - "@final_work.facade.conversation_status"
      - "@final_work.conversation_variation"

  final_work.factory.event_schedule:
    class: FinalWork\FinalWorkBundle\Model\EventSchedule\EventScheduleFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.comment:
    class: FinalWork\FinalWorkBundle\Model\Comment\CommentFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.document:
    class: FinalWork\FinalWorkBundle\Model\Document\DocumentFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.event:
    class: FinalWork\FinalWorkBundle\Model\Event\EventFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.event_address:
    class: FinalWork\FinalWorkBundle\Model\EventAddress\EventAddressFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.event_schedule_template:
    class: FinalWork\FinalWorkBundle\Model\EventScheduleTemplate\EventScheduleTemplateFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.task:
    class: FinalWork\FinalWorkBundle\Model\Task\TaskFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.media_category:
    class: FinalWork\FinalWorkBundle\Model\MediaCategory\MediaCategoryFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.version:
    class: FinalWork\FinalWorkBundle\Model\Version\VersionFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.conversation_message:
    class: FinalWork\FinalWorkBundle\Model\ConversationMessage\ConversationMessageFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.user_group:
    class: FinalWork\FinalWorkBundle\Model\UserGroup\UserGroupFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.work:
    class: FinalWork\FinalWorkBundle\Model\Work\WorkFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.work_category:
    class: FinalWork\FinalWorkBundle\Model\WorkCategory\WorkCategoryFactory
    arguments:
      - '@doctrine.orm.entity_manager'
      -
  final_work.factory.media:
    class: FinalWork\FinalWorkBundle\Model\Media\MediaFactory
    arguments:
      - '@doctrine.orm.entity_manager'

  final_work.factory.user:
    class: FinalWork\FinalWorkBundle\Model\User\UserFactory
    arguments:
      - '@doctrine.orm.entity_manager'