services:
  #   GrafQl
  final_work.graph_ql.resolver.user:
    class: FinalWork\FinalWorkBundle\GraphQL\Resolver\UserResolverMap
    arguments:
      - '@final_work.facade.user'

  final_work.graph_ql.resolver.work:
    class: FinalWork\FinalWorkBundle\GraphQL\Resolver\WorkResolverMap
    arguments:
      - '@final_work.facade.work'
      - '@final_work.facade.work_status'

  final_work.graph_ql.resolver.task:
    class: FinalWork\FinalWorkBundle\GraphQL\Resolver\TaskResolverMap
    arguments:
      - '@final_work.facade.task'

  final_work.graph_ql.resolver.not_doctrine:
    class: FinalWork\FinalWorkBundle\GraphQL\Resolver\NotDoctrineResolverMap

    #   GrafQl Type
  final_work.graph_ql.definition.datetime_type:
    class: FinalWork\FinalWorkBundle\GraphQL\Type\DateTimeType
    tags:
      - { name: overblog_graphql.type, alias: DateTime }