api_key_user:
  resource: api/key_user.yaml
  prefix: /api/key/user

api_key_work:
  resource: api/key_work.yaml
  prefix: /api/key/work

api_key_endpoint:
  resource: api/key_endpoint.yaml
  prefix: /api/key/endpoint

api_key_system_event:
  resource: api/key_system_event.yaml
  prefix: /api/key/system-event

api_key_event:
  resource: api/key_event.yaml
  prefix: /api/key/event

api_key_version:
  resource: api/key_version.yaml
  prefix: /api/key/version

api_key_conversation:
  resource: api/key_conversation.yaml
  prefix: /api/key/conversation
