conversation_list:
  path: /list
  defaults:
    _controller: App\Controller\ConversationController:list
    _seo:
      title: 'app.page.conversation_list'
  methods: [GET, POST]

conversation_detail:
  path: /detail/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\ConversationController:detail
  methods: [GET, POST]

conversation_create:
  path: /create
  defaults:
    _controller: App\Controller\ConversationController:create
    _seo:
      title: 'app.page.message_create'
  methods: [GET, POST]

conversation_work_create:
  path: /create/work/{id_work}/user/{id_user_one}/user/{id_user_two}
  requirements:
    id_work: '%hashid%'
    id_user_one: '%hashid%'
    id_user_two: '%hashid%'
  defaults:
    _controller: App\Controller\ConversationController:createWorkConversation
  methods: [GET, POST]

conversation_message_change_read_status_ajax:
  path: /message/{id}/change/read/status/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\ConversationController:changeReadMessageStatus
  methods: [POST]

conversation_message_all_change_to_read_ajax:
  path: /messages/change-all-to-read/ajax
  defaults:
    _controller: App\Controller\Ajax\ConversationController:readAll
  methods: [POST]

conversation_message_last:
  path: /{id}/last/message
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\ConversationController:lastMessage
  methods: [GET, POST]

conversation_delete_ajax:
  path: /{id}/delete/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\ConversationController:delete
  methods: [POST, DELETE]

conversation_live_ajax:
  path:  /{id}/live
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\ConversationController:liveConversation
  methods: [GET, POST]