document_category_create:
  path: /create
  defaults:
    _controller: App\Domain\DocumentCategory\Controller\DocumentCategoryController::create
    _seo:
      title: 'app.page.information_materials_category_create'
  methods: [GET, POST]

document_category_create_ajax:
  path: /create/ajax
  defaults:
    _controller: App\Domain\DocumentCategory\Controller\Ajax\DocumentCategoryController::create
  methods: [POST]

document_category_edit:
  path: /edit/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\DocumentCategory\Controller\DocumentCategoryController::edit
    _seo:
      title: 'app.page.information_materials_category_edit'
  methods: [GET, POST]

document_category_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\DocumentCategory\Controller\Ajax\DocumentCategoryController::edit
  methods: [POST]

document_category_list:
  path: /list
  defaults:
    _controller: App\Domain\DocumentCategory\Controller\DocumentCategoryController::list
    _seo:
      title: 'app.page.information_materials_category_list'
  methods: [GET, POST]

document_category_delete:
  path: /delete/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\DocumentCategory\Controller\DocumentCategoryController::delete
  methods: [POST, DELETE]

document_category_delete_ajax:
  path: /delete/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\DocumentCategory\Controller\Ajax\DocumentCategoryController::delete
  methods: [POST, DELETE]
