event_schedule_create:
  path: /create
  defaults:
    _controller: App\Domain\EventSchedule\Controller\EventScheduleController::create
    _seo:
      title: 'app.page.event_schedule_create'
  methods: [GET,POST]

event_schedule_detail:
  path: /detail/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\EventSchedule\Controller\EventScheduleController::detail
  methods: [GET]

event_schedule_edit:
  path: /edit/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\EventSchedule\Controller\EventScheduleController::edit
  methods: [GET,POST]

event_schedule_list:
  path: /list
  defaults:
    _controller: App\Domain\EventSchedule\Controller\EventScheduleController::list
    _seo:
      title: 'app.page.event_schedule_list'
  methods: [GET]

event_schedule_clone:
  path: /clone/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\EventSchedule\Controller\EventScheduleController::clone
  methods: [GET,POST]

event_schedule_clone_ajax:
  path: /clone/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\EventSchedule\Controller\Ajax\EventScheduleController::clone
  methods: [GET,POST]

event_schedule_delete:
  path: /delete/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\EventSchedule\Controller\EventScheduleController::delete
  methods: [POST, DELETE]

event_schedule_delete_ajax:
  path: /delete/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\EventSchedule\Controller\Ajax\EventScheduleController::delete
  methods: [POST, DELETE]
    
 