event_calendar_reservation:
  path: /reservation
  defaults:
    _controller: App\Controller\EventCalendarController:reservation
  methods: [GET]

event_calendar_manage:
  path: /manage
  defaults:
    _controller: App\Controller\EventCalendarController:manage
  methods: [GET]

event_calendar_create_ajax:
  path: /create/ajax
  defaults:
    _controller: App\Controller\Ajax\EventCalendarController:create
  methods: [POST]

event_calendar_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\EventCalendarController:edit
  methods: [POST]

event_calendar_reservation_ajax:
  path: /reservation/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\EventCalendarController:eventReservation
  methods: [POST]

event_calendar_events_ajax:
  path: /events/{type}/ajax
  requirements:
    type: "manage|reservation|detail"
  defaults:
    _controller: App\Controller\Ajax\EventCalendarController:getEvent
  methods: [POST]
