profile_show:
  path: /profile
  defaults:
    _controller: App\Model\Profile\Controller\ProfileController::show
    _seo:
      title: 'app.page.profile'
  methods: [GET, POST]

profile_edit:
  path: /profile/edit
  defaults:
    _controller: App\Model\Profile\Controller\ProfileController::edit
    _seo:
      title: 'app.page.profile_edit'
  methods: [GET, POST]

profile_change_image:
  path: /profile/image
  defaults:
    _controller: App\Model\Profile\Controller\ProfileController::changeImage
    _seo:
      title: 'app.page.profile_edit'
  methods: [GET, POST]

profile_delete_image:
  path: /profile/image/delete
  defaults:
    _controller: App\Model\Profile\Controller\ProfileController::deleteImage
  methods: [GET, POST]

profile_change_password:
  path: /profile/change-password
  defaults:
    _controller: App\Model\Profile\Controller\ProfileController::changePassword
    _seo:
      title: 'app.page.profile_edit'
  methods: [GET, POST]

profile_create_image_web_camera_ajax:
  path: /profile/image/create-web-camera/ajax
  defaults:
    _controller: App\Model\Profile\Controller\Ajax\ProfileController::createImageWebCamera
  methods: [POST]
