reset_password_forgot_request:
  path: /request
  defaults:
    _controller: App\Controller\ResetPasswordController:request
  methods: [GET, POST]

reset_password_check_email:
  path: /check-email
  defaults:
    _controller: App\Controller\ResetPasswordController:checkEmail
  methods: [GET]

reset_password_reset:
  path: /reset
  defaults:
    _controller: App\Controller\ResetPasswordController::reset
  methods: [GET, POST]