reset_password_forgot_request:
  path: /request
  defaults:
    _controller: App\Model\ResetPassword\Controller\ResetPasswordController::request
    _seo:
      title: 'app.page.reset_password'
  methods: [GET, POST]

reset_password_check_email:
  path: /check-email
  defaults:
    _controller: App\Model\ResetPassword\Controller\ResetPasswordController::checkEmail
    _seo:
      title: 'app.page.reset_password'
  methods: [GET]

reset_password_reset:
  path: /reset
  defaults:
    _controller: App\Model\ResetPassword\Controller\ResetPasswordController::reset
    _seo:
      title: 'app.page.reset_password'
  methods: [GET, POST]