user_group_create:
  path: /create
  defaults:
    _controller: App\Controller\UserGroupController::create
    _seo:
      title: 'app.page.user_group_create'
  methods: [GET, POST]

user_group_create_ajax:
  path: /create/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\UserGroupController::create
  methods: [GET, POST]

user_group_edit:
  path: /edit/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\UserGroupController::edit
    _seo:
      title: 'app.page.user_group_edit'
  methods: [GET, POST]

user_group_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\UserGroupController::edit
  methods: [GET, POST]

user_group_list:
  path: /list
  defaults:
    _controller: App\Controller\UserGroupController::list
    _seo:
      title: 'app.page.leave_web'
  methods: [GET, POST]

user_group_delete_ajax:
  path: /delete/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\UserGroupController::delete
  methods: [POST, DELETE]