user_create:
  path: /create
  defaults:
    _controller: App\Controller\UserController:create
  methods: [GET, POST]

user_edit:
  path: /edit/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\UserController:edit
  methods: [GET, POST]

user_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\UserController:edit
  methods: [GET, POST]

user_list:
  path: /{type}/list
  requirements:
    type: "author|opponent|consultant|unused"
  defaults:
    _controller: App\Controller\UserController:userList
  methods: [GET, POST]

user_create_ajax:
  path: /create/ajax
  defaults:
    _controller: App\Controller\Ajax\UserController:create
  methods: [POST]