version_create:
  path: /{id}/version/create
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\Version\Controller\VersionController::create
    _seo:
      title: 'app.page.version_add'
  methods: [GET,POST]

version_create_ajax:
  path: /{id}/version/create/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\Version\Controller\Ajax\VersionController::create
  methods: [POST]

version_edit:
  path: /{id_work}/version/edit/{id_media}
  requirements:
    id_work: '%hashid%'
    id_media: '%hashid%'
  defaults:
    _controller: App\Domain\Version\Controller\VersionController::edit
    _seo:
      title: 'app.page.version_edit'
  methods: [GET,POST]

version_edit_ajax:
  path: /{id_work}/version/edit/{id_media}/ajax
  requirements:
    id_work: '%hashid%'
    id_media: '%hashid%'
  defaults:
    _controller: App\Domain\Version\Controller\Ajax\VersionController::edit
  methods: [POST]

version_download:
  path:     /{id_work}/version/download/{id_media}
  requirements:
    id_work: '%hashid%'
    id_media: '%hashid%'
  defaults:
    _controller: App\Domain\Version\Controller\VersionController::download
  methods:  [GET,POST]

version_google_download:
  path:     /{id_work}/version/google/download/{id_media}
  requirements:
    id_work: '%hashid%'
    id_media: '%hashid%'
  defaults:
    _controller: App\Domain\Version\Controller\VersionController::downloadGoogle
  methods:  [GET,POST]

version_delete_ajax:
  path:  /{id_work}/version/delete/{id_media}/ajax
  requirements:
    id_work: '%hashid%'
    id_media: '%hashid%'
  defaults:
    _controller: App\Domain\Version\Controller\Ajax\VersionController::delete
  methods:  [POST, DELETE]
