work_category_create:
  path: /create
  defaults:
    _controller: App\Domain\WorkCategory\Controller\WorkCategoryController::create
    _seo:
      title: 'app.page.work_category_create'
  methods: [GET, POST]

work_category_create_ajax:
  path: /create/ajax
  defaults:
    _controller: App\Domain\WorkCategory\Controller\Ajax\WorkCategoryController::create
  methods: [POST]

work_category_edit:
  path: /edit/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\WorkCategory\Controller\WorkCategoryController::edit
    _seo:
      title: 'app.page.work_category_edit'
  methods: [GET, POST]

work_category_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\WorkCategory\Controller\Ajax\WorkCategoryController::edit
  methods: [POST]

work_category_list:
  path: /list
  defaults:
    _controller: App\Domain\WorkCategory\Controller\WorkCategoryController::list
    _seo:
      title: 'app.page.work_category_list'
  methods: [GET, POST]

work_category_delete:
  path: /delete/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\WorkCategory\Controller\WorkCategoryController::delete
  methods: [POST, DELETE]

work_category_delete_ajax:
  path: /delete/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Domain\WorkCategory\Controller\Ajax\WorkCategoryController::delete
  methods: [POST, DELETE]
