work_create:
  path: /create
  defaults:
    _controller: App\Controller\WorkController:create
  methods: [GET, POST]

work_create_ajax:
  path: /create/ajax
  defaults:
    _controller: App\Controller\Ajax\WorkController:create
  methods: [POST]

work_edit:
  path: /edit/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\WorkController:edit
  methods: [GET, POST]

work_edit_ajax:
  path: /edit/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\WorkController:edit
  methods: [POST]

work_edit_author:
  path: /{id}/edit/author
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\WorkController:editAuthor
  methods: [GET, POST]

work_edit_author_ajax:
  path: /{id}/edit/author/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\WorkController:editAuthor
  methods: [POST]

work_detail:
  path: /detail/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\WorkController:detail
  methods: [GET]

work_list:
  path: /{type}/list
  requirements:
    type: "supervisor|author|opponent|consultant"
  defaults:
    _controller: App\Controller\WorkController:list
  methods: [GET, POST]

work_delete:
  path: /delete/{id}
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\WorkController:delete
  methods: [POST, DELETE]

work_delete_ajax:
  path: /delete/{id}/ajax
  requirements:
    id: '%hashid%'
  defaults:
    _controller: App\Controller\Ajax\WorkController:delete
  methods: [POST, DELETE]
