services:
  _defaults:
    public: true
    autowire: true

  app.cache.homepage:
    class: App\Cache\HomepageCache
    arguments:
      $cache: '@cache.app'

  App\Cache\HomepageCache: '@app.cache.homepage'
