services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  App\Command\:
    resource: '../../../src/Command'

  App\Model\:
    resource: '../../../src/Model/*/Command'
    public: true