services:
  _defaults:
    public: true
    autowire: true

  app.command.add_user:
    class: App\Command\UserAddCommand
    tags:
      - { name: console.command }

  app.command.delete_user:
    class: App\Command\UserDeleteCommand
    tags:
      - { name: console.command }

  app.command.list_user:
    class: App\Command\UserListCommand
    tags:
      - { name: console.command }

  app.command.email_notification:
    class: App\Command\EmailNotificationQueueCommand
    tags:
      - { name: console.command }

  app.command.task_reminder:
    class: App\Command\TaskRemindDeadlineCommand
    tags:
      - { name: console.command }

  app.command.sync_database_media_with_real_file:
    class: App\Command\SyncDatabaseMediaWithRealFileCommand
    tags:
      - { name: console.command }
