services:
  _defaults:
    autowire: true
    public: true

  #  Controller
  app.controller.version:
    class: App\Controller\VersionController
    calls:
      - [setContainer, ["@service_container"]]

  app.controller.document:
    class: App\Controller\DocumentController
    calls:
      - [setContainer, ["@service_container"]]
