services:
  _defaults:
    autowire: true
    public: true

  App\Controller\:
    resource: '../../../src/Controller'
    public: true
    tags: ['controller.service_arguments']
    calls:
      - [setContainer, ["@service_container"]]

  #  Controller
  app.controller.version:
    class: App\Controller\VersionController
    calls:
      - [setContainer, ["@service_container"]]

  app.controller.document:
    class: App\Controller\DocumentController
    calls:
      - [setContainer, ["@service_container"]]
