services:
  _defaults:
    autowire: true

  app.controller.version:
    class: App\Domain\Version\Controller\VersionController
    calls:
      - [ setContainer, [ '@service_container' ] ]

  app.controller.document:
    class: App\Domain\Document\Controller\DocumentController
    calls:
      - [ setContainer, [ '@service_container' ] ]
