services:
  _defaults:
    public: true
    autowire: true

  App\EventDispatcher\:
    resource: '../../../src/EventDispatcher/'
    exclude: '../../../src/EventDispatcher/GenericEvent'

  App\Model\:
    resource: '../../../src/Model/*/EventDispatcher'
    exclude:
      - '../../../src/Model/*/EventDispatcher/GenericEvent'