services:
  _defaults:
    public: true
    autowire: true

  app.event_dispatcher.work:
    class: App\EventDispatcher\WorkEventDispatcherService

  app.event_dispatcher.version:
    class: App\EventDispatcher\VersionEventDispatcherService

  app.event_dispatcher.document:
    class: App\EventDispatcher\DocumentEventDispatcherService

  app.event_dispatcher.user:
    class: App\EventDispatcher\UserEventDispatcherService

  app.event_dispatcher.event:
    class: App\EventDispatcher\EventEventDispatcherService

  app.event_dispatcher.task:
    class: App\EventDispatcher\TaskEventDispatcherService

  App\EventDispatcher\TaskEventDispatcherService: '@app.event_dispatcher.task'

  app.event_dispatcher.conversation:
    class: App\EventDispatcher\ConversationEventDispatcherService

  app.event_dispatcher.security:
    class: App\EventDispatcher\SecurityDispatcherService

  app.event_dispatcher.widget:
    class: App\EventDispatcher\WidgetEventDispatcherService

  app.event_dispatcher.cache:
    class: App\EventDispatcher\CacheEventDispatcherService

  App\EventDispatcher\CacheEventDispatcherService: '@app.event_dispatcher.cache'
