services:
  _defaults:
    public: true
    autowire: true

  app.event_listener.email_notification.base:
    class: App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber
    arguments:
      $emailNotificationProducer: '@old_sound_rabbit_mq.email_notification_producer'

  App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber: '@app.event_listener.email_notification.base'

  app.event_listener.email_notification.document:
    class: App\Application\EventSubscriber\EmailNotification\DocumentEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.event:
    class: App\Application\EventSubscriber\EmailNotification\EventEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.message:
    class: App\Application\EventSubscriber\EmailNotification\MessageEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.security:
    class: App\Application\EventSubscriber\EmailNotification\SecurityEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.task:
    class: App\Application\EventSubscriber\EmailNotification\TaskEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.user:
    class: App\Application\EventSubscriber\EmailNotification\UserEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.version:
    class: App\Application\EventSubscriber\EmailNotification\VersionEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.work:
    class: App\Application\EventSubscriber\EmailNotification\WorkEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true
