services:
  _defaults:
    public: true
    autowire: true

  App\Domain\EmailNotification\EventSubscriber\BaseEmailNotificationSubscriber:

  App\Domain\EmailNotification\EventSubscriber\DocumentEmailNotificationSubscriber:
    parent: 'App\Domain\EmailNotification\EventSubscriber\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Domain\EmailNotification\EventSubscriber\EventEmailNotificationSubscriber:
    parent: 'App\Domain\EmailNotification\EventSubscriber\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Domain\EmailNotification\EventSubscriber\MessageEmailNotificationSubscriber:
    parent: 'App\Domain\EmailNotification\EventSubscriber\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Domain\EmailNotification\EventSubscriber\SecurityEmailNotificationSubscriber:
    parent: 'App\Domain\EmailNotification\EventSubscriber\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Domain\EmailNotification\EventSubscriber\TaskEmailNotificationSubscriber:
    parent: 'App\Domain\EmailNotification\EventSubscriber\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Domain\EmailNotification\EventSubscriber\UserEmailNotificationSubscriber:
    parent: 'App\Domain\EmailNotification\EventSubscriber\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Domain\EmailNotification\EventSubscriber\VersionEmailNotificationSubscriber:
    parent: 'App\Domain\EmailNotification\EventSubscriber\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Domain\EmailNotification\EventSubscriber\WorkEmailNotificationSubscriber:
    parent: 'App\Domain\EmailNotification\EventSubscriber\BaseEmailNotificationSubscriber'
    autoconfigure: true
