services:
  _defaults:
    public: true
    autowire: true

  App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber:
    arguments:
      $emailNotificationProducer: '@old_sound_rabbit_mq.email_notification_producer'

  App\Application\EventSubscriber\EmailNotification\DocumentEmailNotificationSubscriber:
    parent: 'App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Application\EventSubscriber\EmailNotification\EventEmailNotificationSubscriber:
    parent: 'App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Application\EventSubscriber\EmailNotification\MessageEmailNotificationSubscriber:
    parent: 'App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Application\EventSubscriber\EmailNotification\SecurityEmailNotificationSubscriber:
    parent: 'App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Application\EventSubscriber\EmailNotification\TaskEmailNotificationSubscriber:
    parent: 'App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Application\EventSubscriber\EmailNotification\UserEmailNotificationSubscriber:
    parent: 'App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Application\EventSubscriber\EmailNotification\VersionEmailNotificationSubscriber:
    parent: 'App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber'
    autoconfigure: true

  App\Application\EventSubscriber\EmailNotification\WorkEmailNotificationSubscriber:
    parent: 'App\Application\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber'
    autoconfigure: true
