services:
  app.event_listener.email_notification.base:
    class: App\EventSubscriber\EmailNotification\BaseEmailNotificationSubscriber
    autowire: true
    public: false

  app.event_listener.email_notification.document:
    class: App\EventSubscriber\EmailNotification\DocumentEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.event:
    class: App\EventSubscriber\EmailNotification\EventEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.message:
    class: App\EventSubscriber\EmailNotification\MessageEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.security:
    class: App\EventSubscriber\EmailNotification\SecurityEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.task:
    class: App\EventSubscriber\EmailNotification\TaskEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.user:
    class: App\EventSubscriber\EmailNotification\UserEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.version:
    class: App\EventSubscriber\EmailNotification\VersionEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.work:
    class: App\EventSubscriber\EmailNotification\WorkEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true
