services:
  app.event_listener.email_notification.base:
    class: App\EventListener\EmailNotification\BaseEmailNotificationSubscriber
    arguments:
      - '@app.facade.user'
      - '@twig'
      - '@app.translator'
      - '@app.factory.email_notification_queue'
      - '@danilovl.parameter'
    public: false

  app.event_listener.email_notification.document:
    class: App\EventListener\EmailNotification\DocumentEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.event:
    class: App\EventListener\EmailNotification\EventEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.message:
    class: App\EventListener\EmailNotification\MessageEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.security:
    class: App\EventListener\EmailNotification\SecurityEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.task:
    class: App\EventListener\EmailNotification\TaskEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.user:
    class: App\EventListener\EmailNotification\UserEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.version:
    class: App\EventListener\EmailNotification\VersionEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true

  app.event_listener.email_notification.work:
    class: App\EventListener\EmailNotification\WorkEmailNotificationSubscriber
    parent: 'app.event_listener.email_notification.base'
    autoconfigure: true