services:
  _defaults:
    public: true
    autowire: true

  app.entity_listener.media:
    class: App\EventListener\Entity\MediaUploadListener
    tags:
      - name: doctrine.event_listener
        event: prePersist
        entity: App\Entity\Media
        method: prePersist

      - name: doctrine.event_listener
        event: preUpdate
        entity: App\Entity\Media
        method: preUpdate

      - name: doctrine.event_listener
        event: preRemove
        entity: App\Entity\Media
        method: preRemove

  app.entity_listener.system_event_recipient:
    class: App\EventListener\Entity\SystemEventRecipientListener
    tags:
      - name: doctrine.event_listener
        event: postPersist
        entity: App\Entity\SystemEventRecipient
        method: postPersist
