services:
  app.event_listener.request:
    class: App\Application\EventListener\RequestListener
    autowire: true
    public: false
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
