services:
  app.event_listener.request:
    class: App\EventListener\RequestListener
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
