services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  app.event_subscriber.widget:
    class: App\EventSubscriber\WidgetEventSubscriber

  app.event_subscriber.cache:
    class: App\EventSubscriber\CacheEventSubscriber
    arguments:
      - '@cache.app'
