services:
  _defaults:
    public: true
    autowire: true

  app.facade.conversation_message:
    class: App\Domain\Conversation\Facade\ConversationMessageFacade

  App\Domain\Conversation\Facade\ConversationMessageFacade: '@app.facade.conversation_message'

  app.facade.system_event:
    class: App\Domain\SystemEvent\Facade\SystemEventFacade

  App\Domain\SystemEvent\Facade\SystemEventFacade: '@app.facade.system_event'

  app.facade.system_event_recipient:
    class: App\Domain\SystemEvent\Facade\SystemEventRecipientFacade

  App\Domain\SystemEvent\Facade\SystemEventRecipientFacade: '@app.facade.system_event_recipient'
