services:
  _defaults:
    public: true
    autowire: true

  App\Model\:
    resource: '../../../src/Model/*/Factory'

  app.factory.conversation:
    class: App\Model\Conversation\Factory\ConversationFactory

  App\Model\Conversation\Factory\ConversationFactory: '@app.factory.conversation'
