services:
  _defaults:
    public: true
    autowire: true

  app.factory.conversation:
    class: App\Model\Conversation\ConversationFactory

  App\Model\Conversation\ConversationFactory: '@app.factory.conversation'

  app.factory.event_schedule:
    class: App\Model\EventSchedule\EventScheduleFactory

  app.factory.comment:
    class: App\Model\Comment\CommentFactory

  app.factory.document:
    class: App\Model\Document\DocumentFactory

  app.factory.event:
    class: App\Model\Event\EventFactory

  app.factory.event_address:
    class: App\Model\EventAddress\EventAddressFactory

  app.factory.event_schedule_template:
    class: App\Model\EventScheduleTemplate\EventScheduleTemplateFactory

  app.factory.task:
    class: App\Model\Task\TaskFactory

  app.factory.media_category:
    class: App\Model\MediaCategory\MediaCategoryFactory

  app.factory.version:
    class: App\Model\Version\VersionFactory

  app.factory.conversation_message:
    class: App\Model\ConversationMessage\ConversationMessageFactory

  app.factory.user_group:
    class: App\Model\UserGroup\UserGroupFactory

  app.factory.work:
    class: App\Model\Work\WorkFactory

  app.factory.work_category:
    class: App\Model\WorkCategory\WorkCategoryFactory

  app.factory.media:
    class: App\Model\Media\MediaFactory

  app.factory.user:
    class: App\Model\User\UserFactory

  app.factory.reset_password:
    class: App\Model\ResetPassword\ResetPasswordFactory

  App\Model\ResetPassword\ResetPasswordFactory: '@app.factory.reset_password'

  app.factory.email_notification_queue:
    class: App\Model\EmailNotificationQueue\EmailNotificationQueueFactory

  App\Model\EmailNotificationQueue\EmailNotificationQueueFactory: '@app.factory.email_notification_queue'
