services:
  _defaults:
    public: true
    autowire: true

  app.form.data_grid.user:
    class: App\Form\DataGrid\UserDataGrid

  'App\Form\DataGrid\UserDataGrid': '@app.form.data_grid.user'

  app.form.data_grid.work_category:
    class: App\Form\DataGrid\WorkCategoryDataGrid

  'App\Form\DataGrid\WorkCategoryDataGrid': '@app.form.data_grid.work_category'

  app.form.data_grid.media_category:
    class: App\Form\DataGrid\MediaCategoryDataGrid

  'App\Form\DataGrid\MediaCategoryDataGrid': '@app.form.data_grid.media_category'

  app.form.data_grid.work_status:
    class: App\Form\DataGrid\WorkStatusDataGrid

  'App\Form\DataGrid\WorkStatusDataGrid': '@app.form.data_grid.work_status'
