services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  App\Form\:
    resource: '../../../src/Form'
    exclude:
      - '../../../src/Form/Type'
      - '../../../src/Form/Transformer'
      - '../../../src/Form/EventSubscriber'

  App\Model\:
    resource: '../../../src/Model/*/Form'
    exclude:
      - '../../../src/Model/*/Form/EventSubscriber'

  app.form.locales:
    class: App\Form\Type\LocaleType
    autowire: false
    arguments:
      - '%locales%'
    tags:
      - { name: form.type }

  # Constrains
  app.validator.first_week_day:
    class: App\Form\Constraint\FirstWeekDayValidator
    autowire: false
    arguments:
      - '@app.translator'
    tags:
      - { name: validator.constraint_validator }
