services:
  _defaults:
    public: true
    autowire: true

  app.form_factory.work:
    class: App\Form\Factory\WorkFormFactory

  app.form_factory.work_category:
    class: App\Form\Factory\WorkCategoryFormFactory

  app.form_factory.document_category:
    class: App\Form\Factory\DocumentCategoryFormFactory

  app.form_factory.document:
    class: App\Form\Factory\DocumentFormFactory

  app.form_factory.event_address:
    class: App\Form\Factory\EventAddressFormFactory

  app.form_factory.task:
    class: App\Form\Factory\TaskFormFactory

  app.form_factory.user:
    class: App\Form\Factory\UserFormFactory

  app.form_factory.user_group:
    class: App\Form\Factory\UserGroupFormFactory

  app.form_factory.version:
    class: App\Form\Factory\VersionFormFactory
