services:
  _defaults:
    public: true
    autowire: true

  app.form.work:
    class: App\Form\WorkForm
    tags:
      - { name: form.type }

  app.form.document:
    class: App\Form\DocumentForm
    tags:
      - { name: form.type }

  app.form.conversation_compose_message:
    class: App\Form\ConversationComposeMessageForm
    tags:
      - { name: form.type }

  app.form.locales:
    class: App\Form\Type\LocaleType
    autowire: false
    arguments:
      - '%locales%'
    tags:
      - { name: form.type }

  app.form.profile_media:
    class: App\Form\ProfileMediaForm
    tags:
      - { name: form.type }

  app.form.task_several:
    class: App\Form\TaskSeveralForm
    tags:
      - { name: form.type }

  # Constrains
  app.validator.first_week_day:
    class: App\Form\Constraint\FirstWeekDayValidator
    autowire: false
    arguments:
      - '@app.translator'
    tags:
      - { name: validator.constraint_validator }
