services:
  #  Form
  app.form.work:
    class: App\Form\WorkForm
    autowire: true
    tags:
      - { name: form.type }

  app.form.document:
    class: App\Form\DocumentForm
    autowire: true
    tags:
      - { name: form.type }

  app.form.conversation_compose_message:
    class: App\Form\ConversationComposeMessageForm
    autowire: true
    tags:
      - { name: form.type }

  app.form.locales:
    class: App\Form\Type\LocaleType
    arguments:
      - '%locales%'
    tags:
      - { name: form.type }

  app.form.profile_media:
    class: App\Form\ProfileMediaForm
    autowire: true
    tags:
      - { name: form.type }

  # Constrains
  app.validator.first_week_day:
    class: App\Form\Constraint\FirstWeekDayValidator
    arguments:
      - '@app.translator'
    tags:
      - { name: validator.constraint_validator }
