services:
  extension.listener:
    class: App\EventListener\DoctrineExtensionListener
    arguments:
      - '@security.helper'
      - '@gedmo.listener.loggable'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  gedmo.listener.loggable:
    class: Gedmo\Loggable\LoggableListener
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]
    tags:
      - { name: doctrine.event_subscriber, connection: default }
