services:
  _defaults:
    public: true
    autowire: true

  Gedmo\Loggable\LoggableListener:
    calls:
      - [ setAnnotationReader, [ '@annotation_reader' ] ]
    tags:
      - { name: doctrine.event_subscriber, connection: default }
