services:
  _defaults:
    public: true

  app.homepage_notify.user_profile_information:
    class: App\Util\HomepageNotify\UserProfileInformationNotify
    autowire: true
    public: true

  app.homepage_notify.work_deadline_information:
    class: App\Util\HomepageNotify\WorkDeadlineNotify
    autowire: true
    public: true
