services:
  _defaults:
    public: true
    autowire: true

  # Work

  app.http_handle_api.work.list:
    class: App\Model\Work\Http\Api\WorkListHandle

  App\Model\Work\Http\Api\WorkListHandle: '@app.http_handle_api.work.list'
