services:
  _defaults:
    public: true
    autowire: true

  # Work

  app.http_handle_ajax.conversation.change_read_message_status:
    class: App\Model\Conversation\Http\Ajax\ConversationChangeReadMessageStatusHandle

  app.http_handle_ajax.conversation.read_all:
    class: App\Model\Conversation\Http\Ajax\ConversationReadAllHandle

  app.http_handle_ajax.conversation.delete:
    class: App\Model\Conversation\Http\Ajax\ConversationDeleteHandle

  app.http_handle_ajax.conversation.live:
    class: App\Model\Conversation\Http\Ajax\ConversationLiveHandle

  # Document category

  app.http_handle_ajax.document_category.create:
    class: App\Model\DocumentCategory\Http\Ajax\DocumentCategoryCreateHandle

  app.http_handle_ajax.document_category.edit:
    class: App\Model\DocumentCategory\Http\Ajax\DocumentCategoryEditHandle

  app.http_handle_ajax.document_category.delete:
    class: App\Model\DocumentCategory\Http\Ajax\DocumentCategoryDeleteHandle

  # Document

  app.http_handle_ajax.document.create:
    class: App\Model\Document\Http\Ajax\DocumentCreateHandle

  app.http_handle_ajax.document.edit:
    class: App\Model\Document\Http\Ajax\DocumentEditHandle

  app.http_handle_ajax.document.delete:
    class: App\Model\Document\Http\Ajax\DocumentDeleteHandle

  app.http_handle_ajax.document.change_active:
    class: App\Model\Document\Http\Ajax\DocumentChangeActiveHandle

  # Event address

  app.http_handle_ajax.event_address.create:
    class: App\Model\EventAddress\Http\Ajax\EventAddressCreateHandle

  app.http_handle_ajax.event_address.edit:
    class: App\Model\EventAddress\Http\Ajax\EventAddressEditHandle

  app.http_handle_ajax.event_address.delete:
    class: App\Model\EventAddress\Http\Ajax\EventAddressDeleteHandle

  # Event calendar

  app.http_handle_ajax.event_calendar.create:
    class: App\Model\EventCalendar\Http\Ajax\EventCalendarCreateHandle

  app.http_handle_ajax.event_calendar.edit:
    class: App\Model\EventCalendar\Http\Ajax\EventCalendarEditHandle

  app.http_handle_ajax.event_calendar.event_reservation:
    class: App\Model\EventCalendar\Http\Ajax\EventCalendarEventReservationHandle

  app.http_handle_ajax.event_calendar.get_event:
    class: App\Model\EventCalendar\Http\Ajax\EventCalendarGetEventHandle

  # Event

  app.http_handle_ajax.event.get_event:
    class: App\Model\Event\Http\Ajax\EventGetEventHandle

  app.http_handle_ajax.event.edit:
    class: App\Model\Event\Http\Ajax\EventEditHandle

  app.http_handle_ajax.event.delete:
    class: App\Model\Event\Http\Ajax\EventDeleteHandle

  # Event schedule

  app.http_handle_ajax.event_schedule.clone:
    class: App\Model\EventSchedule\Http\Ajax\EventScheduleCloneHandle

  app.http_handle_ajax.event_schedule.delete:
    class: App\Model\EventSchedule\Http\Ajax\EventScheduleDeleteHandle

  # Profile

  app.http_handle_ajax.profile.create_image_web_camera:
    class: App\Model\Profile\Http\Ajax\ProfileCreateImageWebCameraHandle

  # System event

  app.http_handle_ajax.system_event.viewed:
    class: App\Model\SystemEvent\Http\Ajax\SystemEventViewedHandle

  app.http_handle_ajax.system_event.viewed_all:
    class: App\Model\SystemEvent\Http\Ajax\SystemEventViewedAllHandle

  # Task

  app.http_handle_ajax.task.create:
    class: App\Model\Task\Http\Ajax\TaskCreateHandle

  app.http_handle_ajax.task.create_several:
    class: App\Model\Task\Http\Ajax\TaskCreateSeveralHandle

  app.http_handle_ajax.task.edit:
    class: App\Model\Task\Http\Ajax\TaskEditHandle

  app.http_handle_ajax.task.delete:
    class: App\Model\Task\Http\Ajax\TaskDeleteHandle

  app.http_handle_ajax.task.change_status:
    class: App\Model\Task\Http\Ajax\TaskChangeStatusHandle

  app.http_handle_ajax.task.complete_all:
    class: App\Model\Task\Http\Ajax\TaskCompleteAllHandle

  app.http_handle_ajax.task.notify_complete:
    class: App\Model\Task\Http\Ajax\TaskNotifyCompleteHandle

  # User

  app.http_handle_ajax.user.create:
    class: App\Model\User\Http\Ajax\UserCreateHandle

  app.http_handle_ajax.user.edit:
    class: App\Model\User\Http\Ajax\UserEditHandle

  # User group

  app.http_handle_ajax.user_group.create:
    class: App\Model\UserGroup\Http\Ajax\UserGroupCreateHandle

  app.http_handle_ajax.user_group.edit:
    class: App\Model\UserGroup\Http\Ajax\UserGroupEditHandle

  app.http_handle_ajax.user_group.delete:
    class: App\Model\UserGroup\Http\Ajax\UserGroupDeleteHandle

  # Version

  app.http_handle_ajax.version.create:
    class: App\Model\Version\Http\Ajax\VersionCreateHandle

  app.http_handle_ajax.version.edit:
    class: App\Model\Version\Http\Ajax\VersionEditHandle

  app.http_handle_ajax.version.delete:
    class: App\Model\Version\Http\Ajax\VersionDeleteHandle

  # Widget

  app.http_handle_ajax.widget.live:
    class: App\Model\Widget\Http\Ajax\WidgetLiveHandle

  # Work category

  app.http_handle_ajax.work_category.create:
    class: App\Model\WorkCategory\Http\Ajax\WorkCategoryCreateHandle

  app.http_handle_ajax.work_category.edit:
    class: App\Model\WorkCategory\Http\Ajax\WorkCategoryEditHandle

  app.http_handle_ajax.work_category.delete:
    class: App\Model\WorkCategory\Http\Ajax\WorkCategoryDeleteHandle

  # Work

  app.http_handle_ajax.work.create:
    class: App\Model\Work\Http\Ajax\WorkCreateHandle

  app.http_handle_ajax.work.edit:
    class: App\Model\Work\Http\Ajax\WorkEditHandle

  app.http_handle_ajax.work.edit_author:
    class: App\Model\Work\Http\Ajax\WorkEditAuthorHandle

  app.http_handle_ajax.work.delete:
    class: App\Model\Work\Http\Ajax\WorkDeleteHandle