services:
  _defaults:
    public: true
    autowire: true

  app.redirect_to_preferred_locale_listener:
    class: App\Application\EventListener\RedirectToPreferredLocaleListener
    arguments:
      $locales: '%locales%'
      $defaultLocale: '%locale%'

  app.conversation:
    class: App\Domain\Conversation\Service\ConversationService

  App\Domain\Conversation\Service\ConversationService: '@app.conversation'

  app.conversation_variation:
    class: App\Domain\Conversation\Service\ConversationVariationService

  App\Domain\Conversation\Service\ConversationVariationService: '@app.conversation_variation'

  app.conversation_status:
    class: App\Domain\Conversation\Service\ConversationStatusService

  App\Domain\Conversation\Service\ConversationStatusService: '@app.conversation_status'

  app.entity_manager:
    class: App\Application\Service\EntityManagerService

  App\Application\Service\EntityManagerService: '@app.entity_manager'

  #   ParamConverter
  hashids.converter:
    class: App\Application\EventListener\HashidsParamConverterListener
    tags:
      - { name: request.param_converter, priority: 1, converter: hashids.converter }

