services:
  _defaults:
    public: true
    autowire: true

  app.redirect_to_preferred_locale_listener:
    class: App\EventListener\RedirectToPreferredLocaleListener
    arguments:
      $locales: '%locales%'
      $defaultLocale: '%locale%'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  app.mailer:
    class: App\Service\MailerService

  App\Service\MailerService: '@app.mailer'

  app.translator:
    class: App\Service\TranslatorService
    arguments:
      $defaultLocale: '%locale%'

  App\Service\TranslatorService: '@app.translator'

  app.user_password_encoder:
    class: Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher

  app.reset_password:
    class: App\Service\ResetPasswordService

  app.user:
    class: App\Service\User\UserService

  App\Service\User\UserService: '@app.user'

  app.user_work:
    class: App\Service\User\UserWorkService

  App\Service\User\UserWorkService: '@app.user_work'

  app.work:
    class: App\Service\Work\WorkService

  App\Service\Work\WorkService: '@app.work'

  app.task:
    class: App\Service\Task\TaskService

  App\Service\Task\TaskService: '@app.task'

  app.conversation:
    class: App\Service\Conversation\ConversationService

  App\Service\Conversation\ConversationService: '@app.conversation'

  app.conversation_variation:
    class: App\Service\Conversation\ConversationVariationService

  App\Service\Conversation\ConversationVariationService: '@app.conversation_variation'

  app.conversation_status:
    class: App\Service\Conversation\ConversationStatusService

  App\Service\Conversation\ConversationStatusService: '@app.conversation_status'

  app.stream.conversation:
    class: App\Service\Conversation\ConversationStreamService

  app.widget:
    class: App\Service\Widget\WidgetManagerService

  App\Service\Widget\WidgetManagerService: '@app.widget'

  app.stream.widget:
    class: App\Service\Widget\WidgetStreamService

  app.system_event_link_generator:
    class: App\Service\SystemEventLinkGeneratorService
    tags:
      - { name: twig.runtime }

  app.paginator:
    class: App\Service\PaginatorService
    shared: false

  App\Service\PaginatorService: '@app.paginator'

  app.work.detail_tab:
    class: App\Service\Work\WorkDetailTabService

  app.work.list:
    class: App\Service\Work\WorkListService

  App\Service\Work\WorkListService: '@app.work.list'

  app.seo_page:
    class: App\Service\SeoPageService

  App\Service\SeoPageService: '@app.seo_page'

  app.date:
    class: App\Service\DateService

  app.entity_manager:
    class: App\Service\EntityManagerService

  App\Service\EntityManagerService: '@app.entity_manager'

  app.resize_image:
    class: App\Service\ResizeImageService

  App\Service\ResizeImageService: '@app.resize_image'

  app.task_status:
    class: App\Service\Task\TaskStatusService

  App\Service\Task\TaskStatusService: '@app.task_status'

  #   ParamConverter
  hashids.converter:
    class: App\EventListener\HashidsParamConverterListener
    tags:
      - { name: request.param_converter, priority: 1, converter: hashids.converter }

  #  Transformer
  app.transformer.api:
    class: App\Transformer\Api\Transformer

  app.password_updater:
    class: App\Service\PasswordUpdater
