services:
  _defaults:
    public: true
    autowire: true

  app.redirect_to_preferred_locale_listener:
    class: App\Domain\User\EventListener\RedirectToPreferredLocaleListener
    arguments:
      $locales: '%locales%'
      $defaultLocale: '%locale%'

  app.conversation:
    class: App\Domain\Conversation\Service\ConversationService

  App\Domain\Conversation\Service\ConversationService: '@app.conversation'

  app.conversation_variation:
    class: App\Domain\Conversation\Service\ConversationVariationService

  App\Domain\Conversation\Service\ConversationVariationService: '@app.conversation_variation'

  app.conversation_status:
    class: App\Domain\Conversation\Service\ConversationStatusService

  App\Domain\Conversation\Service\ConversationStatusService: '@app.conversation_status'

  Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler:
    factory:   ['@App\Infrastructure\Log\ElasticsearchLogstashHandlerFactory', create]
    arguments:
      $endpoint: '%env(ELASTICSEARCH_URL)%'
      $index: 'monolog'
      $bubble: true
      $elasticsearchVersion: '8.9.0'
      $elasticUsername: '%env(ELASTICSEARCH_USERNAME)%'
      $elasticPassword: '%env(ELASTICSEARCH_PASSWORD)%'
