services:
  app.middleware.ajax.request:
    class: App\EventListener\Middleware\AjaxRequestListener
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}
