services:
  _defaults:
    public: false

  app.profiler:
    class: App\Infrastructure\Config\Collector\SystemInfoCollector
    arguments:
      - '%system_info%'
    tags:
      - { name: data_collector, id: final_work_info, template: 'other/profiler/template.html.twig' }
