services:
  _defaults:
    public: true
    autowire: true

  app.rabbit_mq.consumer.email_notification:
    class: App\Application\RabbitMq\Consumer\EmailNotificationConsumer

  App\Application\RabbitMq\Consumer\EmailNotificationConsumer: '@app.rabbit_mq.consumer.email_notification'
