services:
  _defaults:
    public: true

  redis:
    class: Redis
    public: false
    calls:
      - method: connect
        arguments:
          - '%env(REDIS_HOSTNAME)%'
          - '%env(REDIS_PORT)%'
      - method: select
        arguments:
          - 13

  doctrine_cache.providers.redis_provider:
    class: App\Application\Redis\Provider\RedisCache
    calls:
      - ['setRedis', ['@redis']]
      - ['setNamespace', ['DoctrineSecondLevelCache']]
    tags:
      - { name: snc_redis.client }

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@redis'
