services:
  doctrine_cache.providers.redis_provider:
    class: App\Redis\Provider\RedisCache
    calls:
      - ['setRedis', ['@redis']]
      - ['setNamespace', ['DoctrineSecondLevelCache']]
    tags:
      - { name: snc_redis.client }

  redis:
    class: Redis
    public: false
    calls:
      - method: connect
        arguments:
          - '127.0.0.1'
      - method: select
        arguments:
          - 13 # change database by index