services:
  _defaults:
    public: true

  redis_session:
    class: Predis\Client
    public: false
    arguments:
      $parameters:
        host: '%env(REDIS_HOSTNAME)%'
        port: '%env(REDIS_PORT)%'
        database: 12
      $options: []

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@redis_session'
