services:
  _defaults:
    public: true

  doctrine_cache.providers.redis_provider:
    class: App\Redis\Provider\RedisCache
    calls:
      - ['setRedis', ['@redis']]
      - ['setNamespace', ['DoctrineSecondLevelCache']]
    tags:
      - { name: snc_redis.client }

  redis:
    class: Redis
    public: false
    calls:
      - method: connect
        arguments:
          - '%env(REDIS_HOSTNAME)%'
          - '%env(REDIS_PORT)%'
      - method: select
        arguments:
          - 13 # change database by index