services:
  _defaults:
    public: true
    autowire: true

  #   Authenticator
  app.authenticator:
    class: App\Domain\Security\Authenticator\AppAuthenticator

  app.authenticator.api_key:
    class: App\Domain\Security\Authenticator\ApiAuthenticator

  #   Provider
  app.provider.user:
    class: App\Domain\Security\Provider\AppUserProvider

  app.provider.api_key:
    class: App\Domain\Security\Provider\ApiKeyUserProvider
