services:
  _defaults:
    public: true
    autowire: true

  app.event_listener.system_notification.base:
    class: App\EventSubscriber\SystemEvent\BaseSystemEventSubscriber

  app.event_listener.system_notification.document:
    class: App\EventSubscriber\SystemEvent\DocumentSystemEventSubscriber
    parent: 'app.event_listener.system_notification.base'
    autoconfigure: true

  app.event_listener.system_notification.event:
    class: App\EventSubscriber\SystemEvent\EventSystemEventSubscriber
    parent: 'app.event_listener.system_notification.base'
    autoconfigure: true

  app.event_listener.system_notification.message:
    class: App\EventSubscriber\SystemEvent\MessageSystemEventSubscriber
    parent: 'app.event_listener.system_notification.base'
    autoconfigure: true

  app.event_listener.system_notification.task:
    class: App\EventSubscriber\SystemEvent\TaskSystemEventSubscriber
    parent: 'app.event_listener.system_notification.base'
    autoconfigure: true

  app.event_listener.system_notification.user:
    class: App\EventSubscriber\SystemEvent\UserSystemEventSubscriber
    parent: 'app.event_listener.system_notification.base'
    autoconfigure: true

  app.event_listener.system_notification.version:
    class: App\EventSubscriber\SystemEvent\VersionSystemEventSubscriber
    parent: 'app.event_listener.system_notification.base'
    autoconfigure: true

  app.event_listener.system_notification.work:
    class: App\EventSubscriber\SystemEvent\WorkSystemEventSubscriber
    parent: 'app.event_listener.system_notification.base'
    autoconfigure: true
