services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  App\Twig\:
    resource: '../../../src/Twig'

  App\Twig\ChangeLanguageExtension:
    arguments:
      - '%locales%'
    tags:
      - { name: twig.extension }

  App\Twig\Runtime\AwayRuntime:
    arguments:
      - '@router'
      - '%domain%'
    tags:
      - { name: twig.runtime }

  App\Twig\Runtime\HomepageNotifyWidgetRuntime:
    arguments:
      $container: '@service_container'
    tags:
      - { name: twig.runtime }

  App\Twig\Runtime\SeoRuntime:
    tags:
      - { name: twig.runtime }

  App\Twig\Runtime\WorkRuntime:
    tags:
      - { name: twig.runtime }

  App\Twig\Runtime\UserRuntime:
    tags:
      - { name: twig.runtime }

  App\Twig\Runtime\ConversationRuntime:
    tags:
      - { name: twig.runtime }

  App\Twig\Runtime\TaskRuntime:
    tags:
      - { name: twig.runtime }