services:
  _defaults:
    public: true
    autowire: true

  App\Domain\Widget\WidgetItem\UnreadConversationMessageWidget:
    tags:
      - { name: app.widgets, alias: unread_conversation_message }

  App\Domain\Widget\WidgetItem\UnreadSystemEventWidget:
    tags:
      - { name: app.widgets, alias: unread_system_event }

  App\Domain\Widget\WidgetItem\LocalesWidget:
    arguments:
      $locales: '%locales%'
    tags:
      - { name: app.widgets, alias: locales }

  App\Domain\Widget\WidgetItem\MenuWidget:
    arguments:
      $menuConfig: '%menu%'
    tags:
      - { name: app.widgets, alias: menu }

  App\Domain\Widget\WidgetItem\UserProfileInformationNotifyWidget:
  App\Domain\Widget\WidgetItem\WorkDeadlineNotifyWidget:
