services:
  app.widget.unread_conversation_message:
    class: App\Widget\UnreadConversationMessageWidget
    autowire: true
    public: true
    tags:
      - { name: app.widgets, alias: unread_conversation_message }

  App\Widget\UnreadConversationMessageWidget: '@app.widget.unread_conversation_message'

  app.widget.unread_system_event:
    class: App\Widget\UnreadSystemEventWidget
    autowire: true
    public: true
    tags:
      - { name: app.widgets, alias: unread_system_event }

  App\Widget\UnreadSystemEventWidget: '@app.widget.unread_system_event'

  app.widget.locales:
    class: App\Widget\LocalesWidget
    autowire: true
    public: true
    arguments:
      $locales: '%locales%'
    tags:
      - { name: app.widgets, alias: locales }

  app.widget.menu:
    class: App\Widget\MenuWidget
    autowire: true
    public: true
    arguments:
      $menuConfig: '%menu%'
    tags:
      - { name: app.widgets, alias: menu }

  app.event_subscriber.widget:
    class: App\EventSubscriber\WidgetEventSubscriber
    autoconfigure: true
    autowire: true

  app.widget.user_profile_information:
    class: App\Widget\UserProfileInformationNotifyWidget
    autowire: true
    public: true

  app.widget.work_deadline_information:
    class: App\Widget\WorkDeadlineNotifyWidget
    autowire: true
    public: true
