services:
  _defaults:
    public: true
    autowire: true

  app.widget.unread_conversation_message:
    class: App\Application\Widget\UnreadConversationMessageWidget
    tags:
      - { name: app.widgets, alias: unread_conversation_message }

  App\Application\Widget\UnreadConversationMessageWidget: '@app.widget.unread_conversation_message'

  app.widget.unread_system_event:
    class: App\Application\Widget\UnreadSystemEventWidget
    tags:
      - { name: app.widgets, alias: unread_system_event }

  App\Application\Widget\UnreadSystemEventWidget: '@app.widget.unread_system_event'

  app.widget.locales:
    class: App\Application\Widget\LocalesWidget
    arguments:
      $locales: '%locales%'
    tags:
      - { name: app.widgets, alias: locales }

  app.widget.menu:
    class: App\Application\Widget\MenuWidget
    arguments:
      $menuConfig: '%menu%'
    tags:
      - { name: app.widgets, alias: menu }

  app.widget.user_profile_information:
    class: App\Application\Widget\UserProfileInformationNotifyWidget

  app.widget.work_deadline_information:
    class: App\Application\Widget\WorkDeadlineNotifyWidget
