name: Cypress

on:
 - push
 - workflow_dispatch

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: |
          docker network create dockernet
          docker-compose -f docker-compose.yml up -d

      - name: Install dependencies
        run: |
          docker-compose exec -T php sh bin/composer-first-install.sh
          docker-compose exec -T php php bin/console doctrine:database:import docker/mysql/data/dump.sql
          docker-compose exec -T node sh bin/npm-first-install.sh

      - name: Run tests
        run: docker-compose exec -T node npm run cypress:run

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml down
