name: phpunit|phpstan|cs-fixer

on:
  - workflow_dispatch

jobs:
  code-quality:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Cache vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor-${{hashFiles('composer.lock')}}
          restore-keys: vendor-${{hashFiles('composer.lock')}}

      - name: Install dependencies
        run: composer install --ignore-platform-reqs --no-scripts

      - name: Run warm-up-container
        run: composer warm-up-container

      - name: Run cs-fixer-check
        run: composer cs-fixer-check

      - name: Run phpstan
        run: composer phpstan

      - name: Run tests
        run: composer test-unit

  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: code-quality

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start containers
        uses: ./.github/actions/start-containers

      - name: Check docker api
        uses: ./.github/actions/check-docker-api

      - name: Add kibana user
        uses: ./.github/actions/add-kibana-user

      - name: Cache vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor-${{hashFiles('composer.lock')}}
          restore-keys: vendor-${{hashFiles('composer.lock')}}

      - name: Composer install
        uses: ./.github/actions/composer-install

      - name: Run kernel tests
        uses: ./.github/actions/run-integration-test

      - name: View dev log file
        if: always()
        uses: ./.github/actions/view-dev-log-file

      - name: View dev error log file
        if: always()
        uses: ./.github/actions/view-dev-error-log-file

      - name: Stop containers
        if: always()
        uses: ./.github/actions/stop-containers
