name: Phpunit

on:
  - workflow_dispatch

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start containers
        run: |
          docker network create dockernet
          docker-compose -f docker-compose.yml up -d

      - name: Install dependencies
        run: |
          docker-compose exec -T php sh bin/composer-first-install.sh

      - name: Elastica populate(elastica network bug)
        run: docker-compose exec -T php php bin/console fos:elastica:populate

      - name: Run tests
        run: docker-compose exec -T php composer phpunit

      - name: View log files
        if: always()
        run: |
          docker-compose exec -T php cat var/log/prod.log || true
          docker-compose exec -T php cat var/log/dev.log || true

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml down
